// Provider directory, high-cost patients, referral list, quality measures, specialist providers
import type { Provider, SpecialistProvider, RiskTier } from './mockData.types';

// ── PROVIDERS ──────────────────────────────────────────────
export const mockProviders: Provider[] = [
  {
    id: 'prov-001',
    npi: '1234567890',
    name: 'Dr. Amara Osei',
    specialty: 'Cardiology',
    networkTier: 'Preferred',
    costPercentile: 28,
    qualityScore: 94,
    acceptingNewPatients: true,
    affiliatedFacility: 'Northwestern Memorial Hospital',
    distance: 2.4,
    starsRating: 4.8,
    phone: '(312) 926-2000',
    address: '251 E. Huron St',
    city: 'Chicago',
    state: 'IL',
    zip: '60611',
    boardCertified: true,
    languagesSpoken: ['English', 'Twi'],
    avgWaitDays: 7,
    patientSatisfaction: 96,
    vbcAligned: true,
  },
  {
    id: 'prov-002',
    npi: '2345678901',
    name: 'Dr. Sofia Reinholt',
    specialty: 'Endocrinology',
    networkTier: 'Preferred',
    costPercentile: 35,
    qualityScore: 91,
    acceptingNewPatients: true,
    affiliatedFacility: 'University of Chicago Medicine',
    distance: 5.1,
    starsRating: 4.6,
    phone: '(773) 702-1000',
    address: '5841 S. Maryland Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60637',
    boardCertified: true,
    languagesSpoken: ['English', 'Spanish', 'Swedish'],
    avgWaitDays: 12,
    patientSatisfaction: 93,
    vbcAligned: true,
  },
  {
    id: 'prov-003',
    npi: '3456789012',
    name: 'Dr. Marcus Weatherington',
    specialty: 'Pulmonology',
    networkTier: 'In-Network',
    costPercentile: 52,
    qualityScore: 82,
    acceptingNewPatients: true,
    affiliatedFacility: 'Rush University Medical Center',
    distance: 3.8,
    starsRating: 4.2,
    phone: '(312) 942-5000',
    address: '1620 W. Harrison St',
    city: 'Chicago',
    state: 'IL',
    zip: '60612',
    boardCertified: true,
    languagesSpoken: ['English'],
    avgWaitDays: 18,
    patientSatisfaction: 88,
    vbcAligned: false,
  },
  {
    id: 'prov-004',
    npi: '4567890123',
    name: 'Dr. Priya Venkataraman',
    specialty: 'Nephrology',
    networkTier: 'Preferred',
    costPercentile: 22,
    qualityScore: 97,
    acceptingNewPatients: false,
    affiliatedFacility: 'Northwestern Memorial Hospital',
    distance: 2.4,
    starsRating: 4.9,
    phone: '(312) 926-8400',
    address: '675 N. St. Clair St',
    city: 'Chicago',
    state: 'IL',
    zip: '60611',
    boardCertified: true,
    languagesSpoken: ['English', 'Tamil', 'Hindi'],
    avgWaitDays: 21,
    patientSatisfaction: 98,
    vbcAligned: true,
  },
  {
    id: 'prov-005',
    npi: '5678901234',
    name: 'Dr. Jerome Blackwood',
    specialty: 'Orthopedics',
    networkTier: 'In-Network',
    costPercentile: 68,
    qualityScore: 78,
    acceptingNewPatients: true,
    affiliatedFacility: 'Advocate Illinois Masonic',
    distance: 4.2,
    starsRating: 3.9,
    phone: '(773) 975-1600',
    address: '836 W. Wellington Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60657',
    boardCertified: true,
    languagesSpoken: ['English'],
    avgWaitDays: 14,
    patientSatisfaction: 84,
    vbcAligned: false,
  },
  {
    id: 'prov-006',
    npi: '6789012345',
    name: 'Dr. Fatima Al-Rashidi',
    specialty: 'Ophthalmology',
    networkTier: 'Preferred',
    costPercentile: 31,
    qualityScore: 89,
    acceptingNewPatients: true,
    affiliatedFacility: 'Illinois Eye and Ear Infirmary',
    distance: 1.8,
    starsRating: 4.5,
    phone: '(312) 996-6500',
    address: '1855 W. Taylor St',
    city: 'Chicago',
    state: 'IL',
    zip: '60612',
    boardCertified: true,
    languagesSpoken: ['English', 'Arabic'],
    avgWaitDays: 9,
    patientSatisfaction: 92,
    vbcAligned: true,
  },
  {
    id: 'prov-007',
    npi: '7890123456',
    name: 'Dr. Thomas Kaczmarek',
    specialty: 'Gastroenterology',
    networkTier: 'In-Network',
    costPercentile: 61,
    qualityScore: 80,
    acceptingNewPatients: true,
    affiliatedFacility: 'Loyola University Medical Center',
    distance: 11.2,
    starsRating: 4.0,
    phone: '(708) 216-9000',
    address: '2160 S. First Ave',
    city: 'Maywood',
    state: 'IL',
    zip: '60153',
    boardCertified: true,
    languagesSpoken: ['English', 'Polish'],
    avgWaitDays: 16,
    patientSatisfaction: 86,
    vbcAligned: false,
  },
  {
    id: 'prov-008',
    npi: '8901234567',
    name: 'Dr. Nkechi Eze-Williams',
    specialty: 'Endocrinology',
    networkTier: 'Out-of-Network',
    costPercentile: 84,
    qualityScore: 88,
    acceptingNewPatients: true,
    affiliatedFacility: 'Private Practice',
    distance: 6.7,
    starsRating: 4.4,
    phone: '(312) 555-0199',
    address: '875 N. Michigan Ave, Ste 3400',
    city: 'Chicago',
    state: 'IL',
    zip: '60611',
    boardCertified: true,
    languagesSpoken: ['English', 'Igbo'],
    avgWaitDays: 5,
    patientSatisfaction: 91,
    vbcAligned: false,
  },
  {
    id: 'prov-009',
    npi: '9012345678',
    name: 'Dr. Carlos Mendez-Ruiz',
    specialty: 'Cardiology',
    networkTier: 'In-Network',
    costPercentile: 44,
    qualityScore: 85,
    acceptingNewPatients: true,
    affiliatedFacility: 'Stroger Hospital of Cook County',
    distance: 3.1,
    starsRating: 4.1,
    phone: '(312) 864-6000',
    address: '1969 Ogden Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60612',
    boardCertified: true,
    languagesSpoken: ['English', 'Spanish'],
    avgWaitDays: 10,
    patientSatisfaction: 87,
    vbcAligned: true,
  },
  {
    id: 'prov-010',
    npi: '0123456789',
    name: 'Dr. Linda Kowalczyk',
    specialty: 'Geriatrics',
    networkTier: 'Preferred',
    costPercentile: 19,
    qualityScore: 96,
    acceptingNewPatients: false,
    affiliatedFacility: 'Rush University Medical Center',
    distance: 3.8,
    starsRating: 4.9,
    phone: '(312) 942-6200',
    address: '1620 W. Harrison St',
    city: 'Chicago',
    state: 'IL',
    zip: '60612',
    boardCertified: true,
    languagesSpoken: ['English', 'Polish'],
    avgWaitDays: 28,
    patientSatisfaction: 97,
    vbcAligned: true,
  },
];

// ── HIGH COST PATIENTS for Financial Dashboard ──────────────
export const mockHighCostPatients = [
  {
    id: 'patient-011',
    name: 'Sylvia Montecinos',
    riskTier: 'Critical' as RiskTier,
    pmpm: 3120,
    target: 890,
    variance: 2230,
    topDriver: 'Inpatient',
    interventionStatus: 'Active',
  },
  {
    id: 'patient-001',
    name: 'Margaret Okonkwo',
    riskTier: 'Critical' as RiskTier,
    pmpm: 2840,
    target: 890,
    variance: 1950,
    topDriver: 'Specialty',
    interventionStatus: 'Active',
  },
  {
    id: 'patient-002',
    name: 'Delroy Hutchinson',
    riskTier: 'Critical' as RiskTier,
    pmpm: 2210,
    target: 890,
    variance: 1320,
    topDriver: 'Inpatient',
    interventionStatus: 'In Progress',
  },
  {
    id: 'patient-003',
    name: 'Rosa Evangelista',
    riskTier: 'High' as RiskTier,
    pmpm: 1640,
    target: 890,
    variance: 750,
    topDriver: 'ER',
    interventionStatus: 'Active',
  },
  {
    id: 'patient-004',
    name: 'Bernard Thibodeau',
    riskTier: 'High' as RiskTier,
    pmpm: 1290,
    target: 890,
    variance: 400,
    topDriver: 'Post-Acute',
    interventionStatus: 'Pending',
  },
  {
    id: 'patient-012',
    name: 'Kwame Asantewaa',
    riskTier: 'High' as RiskTier,
    pmpm: 1380,
    target: 890,
    variance: 490,
    topDriver: 'Specialty',
    interventionStatus: 'None',
  },
  {
    id: 'patient-005',
    name: 'Constance Abara',
    riskTier: 'High' as RiskTier,
    pmpm: 1180,
    target: 890,
    variance: 290,
    topDriver: 'Pharmacy',
    interventionStatus: 'Active',
  },
  {
    id: 'patient-006',
    name: 'Walter Przybylski',
    riskTier: 'Moderate' as RiskTier,
    pmpm: 920,
    target: 890,
    variance: 30,
    topDriver: 'Specialty',
    interventionStatus: 'None',
  },
];

// ── REFERRALS (tracking list) ──────────────────────────────
export const mockReferrals: any[] = [
  {
    id: 'ref-001',
    patientId: 'patient-001',
    patientName: 'Margaret Okonkwo',
    referralDate: '2026-04-20',
    specialty: 'Cardiology',
    urgency: 'STAT',
    status: 'In Progress',
    assignedProvider: 'Dr. Amara Osei',
    providerId: 'prov-041',
    providerTier: 'Preferred',
    icdCode: 'I20.9',
    icdDescription: 'Angina pectoris, unspecified',
    submissionChannel: 'EHR Portal',
    submittedDate: '2026-04-21',
    appointmentDate: '2026-04-28',
    closedDate: null,
    outcome: null,
    coordinatorName: 'Linda Marsh',
    notes: 'Patient reports intermittent chest pain. Urgent cardiac workup ordered.',
    daysOpen: 9,
  },
  {
    id: 'ref-002',
    patientId: 'patient-002',
    patientName: 'Delroy Hutchinson',
    referralDate: '2026-04-18',
    specialty: 'Endocrinology',
    urgency: 'Urgent',
    status: 'Assigned',
    assignedProvider: 'Dr. Sofia Reinholt',
    providerId: 'prov-017',
    providerTier: 'In-Network',
    icdCode: 'E11.65',
    icdDescription: 'Type 2 diabetes mellitus with hyperglycemia',
    submissionChannel: 'Fax',
    submittedDate: '2026-04-19',
    appointmentDate: null,
    closedDate: null,
    outcome: null,
    coordinatorName: 'James Park',
    notes: 'A1C 8.2%. Specialist consultation for insulin management.',
    daysOpen: 11,
  },
  {
    id: 'ref-003',
    patientId: 'patient-003',
    patientName: 'Rosa Evangelista',
    referralDate: '2026-04-10',
    specialty: 'Nephrology',
    urgency: 'Urgent',
    status: 'Completed',
    assignedProvider: 'Dr. Priya Venkataraman',
    providerId: 'prov-022',
    providerTier: 'Preferred',
    icdCode: 'N18.3',
    icdDescription: 'Chronic kidney disease, stage 3',
    submissionChannel: 'EHR Portal',
    submittedDate: '2026-04-11',
    appointmentDate: '2026-04-19',
    closedDate: '2026-04-22',
    outcome: 'Seen',
    coordinatorName: 'Linda Marsh',
    notes: 'eGFR 45. Follow-up nephrology visit completed. 90-day recheck recommended.',
    daysOpen: 12,
  },
  {
    id: 'ref-004',
    patientId: 'patient-004',
    patientName: 'Curtis Beaumont',
    referralDate: '2026-04-22',
    specialty: 'Pulmonology',
    urgency: 'Routine',
    status: 'Pending',
    assignedProvider: null,
    providerId: null,
    providerTier: null,
    icdCode: 'J44.1',
    icdDescription: 'Chronic obstructive pulmonary disease with acute exacerbation',
    submissionChannel: null,
    submittedDate: null,
    appointmentDate: null,
    closedDate: null,
    outcome: null,
    coordinatorName: 'James Park',
    notes: 'COPD exacerbation. Pulmonology consult requested for medication adjustment.',
    daysOpen: 7,
  },
  {
    id: 'ref-005',
    patientId: 'patient-005',
    patientName: 'Yolanda Ferreira',
    referralDate: '2026-04-08',
    specialty: 'Orthopedics',
    urgency: 'Routine',
    status: 'Awaiting EMR',
    assignedProvider: 'Dr. Kevin Nakashima',
    providerId: 'prov-033',
    providerTier: 'In-Network',
    icdCode: 'M17.11',
    icdDescription: 'Primary osteoarthritis, right knee',
    submissionChannel: 'Phone',
    submittedDate: '2026-04-09',
    appointmentDate: null,
    closedDate: null,
    outcome: null,
    coordinatorName: 'Sandra Wei',
    notes: 'Knee OA. Awaiting prior auth before scheduling injection appointment.',
    daysOpen: 21,
  },
  {
    id: 'ref-006',
    patientId: 'patient-006',
    patientName: 'Harold Simmons',
    referralDate: '2026-04-05',
    specialty: 'Gastroenterology',
    urgency: 'Routine',
    status: 'Cancelled',
    assignedProvider: null,
    providerId: null,
    providerTier: null,
    icdCode: 'K57.30',
    icdDescription: 'Diverticulosis of large intestine without perforation or abscess',
    submissionChannel: 'Fax',
    submittedDate: '2026-04-06',
    appointmentDate: null,
    closedDate: '2026-04-15',
    outcome: 'Cancelled',
    coordinatorName: 'Sandra Wei',
    notes: 'Patient declined specialist visit. Managing symptomatically with PCP.',
    daysOpen: 10,
  },
];

// ── STARS MEASURES ──────────────────────────────────────────
export const mockSTARSMeasures: any[] = [
  {
    id: 'stars-001',
    measureId: 'C01',
    measureName: 'Breast Cancer Screening',
    domain: 'Screening',
    contractName: 'MA-H1234 Silver Plan',
    currentRating: 3,
    targetRating: 4,
    gapCount: 99,
    bonusEstimate: 247500,
    deadline: '2024-09-30',
    status: 'open',
  },
  {
    id: 'stars-002',
    measureId: 'C02',
    measureName: 'Colorectal Cancer Screening',
    domain: 'Screening',
    contractName: 'MA-H1234 Silver Plan',
    currentRating: 3,
    targetRating: 4,
    gapCount: 146,
    bonusEstimate: 182000,
    deadline: '2024-09-30',
    status: 'in-progress',
  },
  {
    id: 'stars-003',
    measureId: 'D01',
    measureName: 'Diabetes Care — HbA1c Control',
    domain: 'Diabetes',
    contractName: 'MA-H5678 Gold Plan',
    currentRating: 4,
    targetRating: 5,
    gapCount: 72,
    bonusEstimate: 180000,
    deadline: '2024-10-31',
    status: 'open',
  },
  {
    id: 'stars-004',
    measureId: 'MED',
    measureName: 'Medication Adherence — Diabetes',
    domain: 'Medication Adherence',
    contractName: 'MA-H5678 Gold Plan',
    currentRating: 2,
    targetRating: 4,
    gapCount: 203,
    bonusEstimate: 103500,
    deadline: '2024-12-31',
    status: 'open',
  },
];

// ── HEDIS MEASURES ────────────────────────────
export const mockHEDISMeasures: any[] = [
  {
    id: 'hedis-001',
    measureId: 'CDC-H9',
    measureName: 'Diabetes: HbA1c Poor Control',
    domain: 'Diabetes',
    contractName: 'Commercial-PPO-2024',
    complianceRate: 18,
    targetRate: 15,
    patientsDue: 380,
    patientsCompliant: 312,
    dueDate: '2024-09-30',
    evidenceTypes: ['Lab Result', 'Claims'],
    status: 'open',
  },
  {
    id: 'hedis-002',
    measureId: 'CBP',
    measureName: 'Controlling High Blood Pressure',
    domain: 'Cardiovascular',
    contractName: 'Medicare Advantage-H1234',
    complianceRate: 64,
    targetRate: 70,
    patientsDue: 620,
    patientsCompliant: 397,
    dueDate: '2024-10-15',
    evidenceTypes: ['Clinical Documentation', 'Claims'],
    status: 'in-progress',
  },
  {
    id: 'hedis-003',
    measureId: 'COL',
    measureName: 'Colorectal Cancer Screening',
    domain: 'Screening',
    contractName: 'Commercial-PPO-2024',
    complianceRate: 71,
    targetRate: 75,
    patientsDue: 520,
    patientsCompliant: 369,
    dueDate: '2024-11-30',
    evidenceTypes: ['Lab Result', 'Radiology', 'Claims'],
    status: 'open',
  },
  {
    id: 'hedis-004',
    measureId: 'FUH',
    measureName: 'Follow-Up After Hospitalization for Mental Illness',
    domain: 'Behavioral Health',
    contractName: 'Medicaid-MCO-2024',
    complianceRate: 48,
    targetRate: 65,
    patientsDue: 124,
    patientsCompliant: 60,
    dueDate: '2024-09-15',
    evidenceTypes: ['Encounter', 'Claims'],
    status: 'open',
  },
];

// ── MIPS ADJUSTMENTS ──────────────────────────
export const mockMIPSAdjustments: any[] = [
  {
    id: 'mips-001',
    noticeId: 'MIPS-2023-001',
    performanceYear: '2023',
    compositeScore: 82,
    adjustmentPct: 1.88,
    adjustmentAmount: 67400,
    qualityScore: 85,
    promotingInteropScore: 90,
    improvementActScore: 40,
    costScore: 72,
    deadline: '2024-06-30',
    status: 'closed',
    appealEligible: false,
  },
  {
    id: 'mips-002',
    noticeId: 'MIPS-2023-002',
    performanceYear: '2023',
    compositeScore: 58,
    adjustmentPct: -4.5,
    adjustmentAmount: -112000,
    qualityScore: 55,
    promotingInteropScore: 68,
    improvementActScore: 20,
    costScore: 48,
    deadline: '2024-08-15',
    status: 'in-review',
    appealEligible: true,
  },
  {
    id: 'mips-003',
    noticeId: 'MIPS-2023-003',
    performanceYear: '2023',
    compositeScore: 61,
    adjustmentPct: -2.25,
    adjustmentAmount: -91000,
    qualityScore: 60,
    promotingInteropScore: 72,
    improvementActScore: 20,
    costScore: 53,
    deadline: '2024-09-01',
    status: 'open',
    appealEligible: true,
  },
];

// ── SPECIALIST PROVIDERS ──────────────────────────────────────────────────────
export const mockSpecialistProviders: SpecialistProvider[] = [
  {
    id: 'specialist-001',
    name: 'Dr. Emily Rodriguez',
    npi: '1234567890',
    specialty: 'Endocrinology',
    organization: 'Chicago Diabetes & Endocrine Center',
  },
  {
    id: 'specialist-002',
    name: 'Dr. Michael Chen',
    npi: '2345678901',
    specialty: 'Cardiology',
    organization: 'Heart & Vascular Institute',
  },
  {
    id: 'specialist-003',
    name: 'Dr. Sarah Johnson',
    npi: '3456789012',
    specialty: 'Nephrology',
    organization: 'Kidney Care Specialists',
  },
  {
    id: 'specialist-004',
    name: 'Dr. James Williams',
    npi: '4567890123',
    specialty: 'Pulmonology',
    organization: 'Respiratory Health Center',
  },
];

// Get current specialist (simulates logged-in user)
export const getCurrentSpecialist = (): SpecialistProvider => mockSpecialistProviders[0];
