// patientRegistry.data2.ts — James Wilson + Robert Chen
import type { RegistryPatient } from './patientRegistry.types';

export const REGISTRY_PART2: RegistryPatient[] = [
  // ── James Wilson ──────────────────────────────────────────────────────────
  {
    platformId: 'PAT-0087',
    journey: { id: 'CHF_DM_120D', currentDay: 89 },
    household: {
      dependents: [],
      caregiverFor: [
        {
          name: 'Ruth Wilson',
          relation: 'Mother',
          age: 84,
          condition: 'Early-stage Alzheimer disease + Type 2 diabetes',
          clinicalMetric: 'A1C 7.9% - DM management',
          pharmacy: 'Cedar Bluff Pharmacy',
          prescriber: 'Cedar Bluff Regional Medical Center',
          meds: [
            { name: 'Donepezil', dose: '10mg', indication: 'Alzheimer disease' },
            { name: 'Metformin', dose: '1000mg', indication: 'Type 2 Diabetes' },
            { name: 'Lisinopril', dose: '10mg', indication: 'Hypertension' },
          ],
          consentScopeItems: ['Medication list', 'Appointment scheduling', 'Refill coordination'],
          consentExclusions: ['Behavioral health records', 'Third-party disclosure'],
        },
      ],
    },
    fhirId: 'patient/james-wilson-087',
    ehrMrn: 'MRN-0087',
    name: 'James Wilson',
    age: 58,
    gender: 'M',
    dob: '1968-07-14',
    location: 'Rural Route 2, Winner SD 57580',
    phone: '(605) 555-0223',
    pcp: 'Dr. Okonkwo',
    careManager: 'Sarah Johnson',
    careManagerInitials: 'SJ',
    organization: 'Cedar Bluff Regional Medical Center',
    contract: 'Medicaid RHTP Track 3',
    attribution: 'Confirmed · Medicaid RHTP Track 3',
    rafScore: 2.8,
    riskTier: 'High',
    riskLabel: 'High — 67% ER risk',
    erRiskPct: 67,
    hccSuspects: 3,
    hccValue: 18600,
    openCareGaps: 7,
    episodeType: 'Diabetes · CHF',
    episodeStatus: 'Active',
    episodeDaysActive: 89,
    pmpm: 1840,
    pmpmTarget: 1200,
    lastContact: '3 weeks ago',
    bhScreeningLabel: 'PHQ-9',
    bhScore: 8,
    bhScoreLabel: 'PHQ-9 8 — Mild depression',
    auditC: 3,
    bhRisk: 'Low',
    bhReferralStatus: 'Not referred',
    bhProvider: '—',
    burdenScore: 'PAM 2 — Struggling',
    patientGoal: "'Manage my diabetes and stay out of the hospital'",
    transportStatus: 'Limited — 35 miles to clinic',
    foodSecurity: 'SNAP active',
    housingStatus: 'Stable — owns home',
    language: 'English',
    ruralDistance: '35 miles to Cedar Bluff Regional',
    disparityFlag: 'Rural · Low income',
    cohortFlag: 'Diabetes · CHF · Rural SD',
    snapStatus: 'Active',
    digitalAccess: 'Smartphone — limited data plan',
    careGaps: [
      {
        id: 'jw-1',
        domain: 'Clinical',
        name: 'A1C Recheck (Diabetes)',
        status: 'Open',
        daysOpen: 45,
        assignedTo: 'Dr. Okonkwo',
      },
      {
        id: 'jw-2',
        domain: 'Clinical',
        name: 'BNP Lab Panel (CHF)',
        status: 'Open',
        daysOpen: 22,
        assignedTo: 'Dr. Okonkwo',
      },
      {
        id: 'jw-3',
        domain: 'Clinical',
        name: 'Retinal Exam',
        status: 'Open',
        daysOpen: 120,
        assignedTo: 'Dr. Okonkwo',
      },
      {
        id: 'jw-4',
        domain: 'Clinical',
        name: 'Nephropathy Screening',
        status: 'Open',
        daysOpen: 60,
        assignedTo: 'Dr. Okonkwo',
      },
      {
        id: 'jw-5',
        domain: 'BH',
        name: 'PHQ-9 Follow-up',
        status: 'Open',
        daysOpen: 30,
        assignedTo: 'Sarah Johnson',
      },
      {
        id: 'jw-6',
        domain: 'Social',
        name: 'Transportation — Specialist Visits',
        status: 'Open',
        daysOpen: 45,
        assignedTo: 'Sarah Johnson',
      },
      {
        id: 'jw-7',
        domain: 'Social',
        name: 'Medication Adherence Support',
        status: 'In Progress',
        daysOpen: 14,
        assignedTo: 'Sarah Johnson',
      },
    ],
    pathwaySteps: [
      {
        id: 'jwps-1',
        label: 'Diabetes Education',
        status: 'completed',
        date: 'Mar 1',
        metric: 'Completed',
      },
      {
        id: 'jwps-2',
        label: 'CHF Monitoring Setup',
        status: 'completed',
        date: 'Mar 15',
        metric: 'Daily weight log',
      },
      { id: 'jwps-3', label: 'A1C Recheck', status: 'in_progress', metric: 'Goal: <7.5%' },
      { id: 'jwps-4', label: 'Cardiology Referral', status: 'pending', metric: 'CHF management' },
      { id: 'jwps-5', label: 'BH Screening', status: 'pending', metric: 'PHQ-9 follow-up' },
    ],
    aiCopilot:
      'CHF + Diabetes dual management — A1C 45 days overdue, BNP panel 22 days overdue. PHQ-9 8 mild depression — consider BH referral given chronic disease burden. Transportation barrier (35 miles) affects specialist follow-up. Medication adherence support in progress.',
    cdsCards: [
      {
        id: 'cds-james-1',
        indicator: 'warning',
        summary: 'A1C overdue 45 days — diabetes management gap',
        detail:
          'Diabetic A1C recheck is 45 days overdue. Last value not on record. Retinal exam and nephropathy screening also overdue. Bundle labs to reduce patient travel burden.',
      },
      {
        id: 'cds-james-2',
        indicator: 'warning',
        summary: 'BNP panel overdue 22 days — CHF monitoring gap',
        detail:
          'CHF monitoring BNP panel is 22 days overdue. Patient has active CHF episode (89 days). Daily weight log active but no recent lab confirmation of fluid status.',
      },
      {
        id: 'cds-james-3',
        indicator: 'info',
        summary: 'PHQ-9 8 — mild depression, consider BH referral',
        detail:
          'PHQ-9 score 8 indicates mild depression. Chronic disease burden (Diabetes + CHF) increases BH risk. Consider BH referral to address depression and improve medication adherence.',
      },
    ],
    conditions: [
      {
        key: 'jw-c1',
        code: 'I50.32',
        name: 'Chronic systolic heart failure',
        onset: '2022-01',
        status: 'Active',
        source: 'EMR',
      },
      {
        key: 'jw-c2',
        code: 'E11.9',
        name: 'Type 2 diabetes mellitus',
        onset: '2015-04',
        status: 'Active',
        source: 'EMR',
      },
      {
        key: 'jw-c3',
        code: 'I10',
        name: 'Essential (primary) hypertension',
        onset: '2013-08',
        status: 'Active',
        source: 'Claims',
      },
      {
        key: 'jw-c4',
        code: 'F32.0',
        name: 'Major depressive disorder, mild',
        onset: '2024-02',
        status: 'Active',
        source: 'EMR',
      },
    ],
    medications: [
      {
        key: 'jw-m1',
        name: 'Metformin HCl',
        dose: '1000mg',
        frequency: 'BID',
        prescriber: 'Dr. Okonkwo',
        lastFill: '2026-04-10',
        adherence: 0.74,
        ddi: false,
      },
      {
        key: 'jw-m2',
        name: 'Carvedilol',
        dose: '12.5mg',
        frequency: 'BID',
        prescriber: 'Dr. Okonkwo',
        lastFill: '2026-04-01',
        adherence: 0.85,
        ddi: false,
      },
      {
        key: 'jw-m3',
        name: 'Lisinopril',
        dose: '10mg',
        frequency: 'Daily',
        prescriber: 'Dr. Okonkwo',
        lastFill: '2026-04-01',
        adherence: 0.9,
        ddi: false,
      },
      {
        key: 'jw-m4',
        name: 'Furosemide',
        dose: '20mg',
        frequency: 'Daily',
        prescriber: 'Dr. Okonkwo',
        lastFill: '2026-03-18',
        adherence: 0.78,
        ddi: false,
      },
      {
        key: 'jw-m5',
        name: 'Atorvastatin',
        dose: '20mg',
        frequency: 'Nightly',
        prescriber: 'Dr. Okonkwo',
        lastFill: '2026-03-18',
        adherence: 0.82,
        ddi: false,
      },
    ],
    recentOrders: [
      {
        key: 'jw-o1',
        type: 'Lab',
        name: 'HbA1c',
        result: 'Overdue 45 days',
        date: '2026-02-28',
        status: 'Ordered',
        flag: 'High',
      },
      {
        key: 'jw-o2',
        type: 'Lab',
        name: 'BNP Panel',
        result: 'Overdue 22 days',
        date: '2026-03-21',
        status: 'Ordered',
        flag: 'High',
      },
      {
        key: 'jw-o3',
        type: 'Lab',
        name: 'Retinal Exam',
        result: 'Overdue 120 days',
        date: '2025-12-01',
        status: 'Ordered',
        flag: 'High',
      },
      {
        key: 'jw-o4',
        type: 'Referral',
        name: 'Cardiology Consultation',
        result: 'Pending scheduling',
        date: '2026-04-01',
        status: 'Pending',
        flag: null,
      },
    ],
    carePlanDomains: [
      {
        domain: 'Clinical',
        color: '#0043ce',
        icon: 'HeartIcon',
        goals: [
          {
            goal: 'A1C < 7.5% by Q3 2026',
            status: 'in-progress',
            owner: 'Dr. Okonkwo',
            dueDate: '2026-09-30',
            tasks: [
              'Metformin 1000mg BID compliance review',
              'A1C lab recheck',
              'Diabetes education reinforcement',
            ],
          },
          {
            goal: 'CHF BNP panel current',
            status: 'open',
            owner: 'Dr. Okonkwo',
            dueDate: '2026-05-15',
            tasks: ['BNP + CBC lab order', 'Daily weight log review', 'Carvedilol dose assessment'],
          },
        ],
      },
      {
        domain: 'Behavioral Health',
        color: '#6929c4',
        icon: 'SparklesIcon',
        goals: [
          {
            goal: 'PHQ-9 follow-up completed',
            status: 'open',
            owner: 'Sarah Johnson',
            dueDate: '2026-06-30',
            tasks: [
              'PHQ-9 re-assessment',
              'BH referral if score > 10',
              'Medication adherence counseling',
            ],
          },
        ],
      },
      {
        domain: 'Social Needs',
        color: '#b45309',
        icon: 'HomeIcon',
        goals: [
          {
            goal: 'Transportation barrier addressed for specialist visits',
            status: 'open',
            owner: 'Sarah Johnson',
            dueDate: '2026-07-31',
            tasks: ['Medicaid NEMT enrollment', 'Coordinate cardiology transport'],
          },
          {
            goal: 'Medication adherence support enrolled',
            status: 'in-progress',
            owner: 'Sarah Johnson',
            dueDate: '2026-05-31',
            tasks: ['Pill organizer provided', 'Weekly check-in calls scheduled'],
          },
        ],
      },
    ],
  },

  // ── Robert Chen ───────────────────────────────────────────────────────────
  {
    platformId: 'PAT-0103',
    journey: { id: 'CKD_180D', currentDay: 156 },
    household: {
      dependents: [
        {
          name: 'Kevin Chen',
          relation: 'Son',
          age: 20,
          dob: '2005',
          plan: 'Medicaid (student)',
          consent: 'Adult dependent - self-consent',
          gaps: [
            {
              label: 'Asthma PCP Re-establishment',
              urgency: 'high',
              detail: 'Lapsed PCP - controller refill at risk',
            },
          ],
          coordinatedOutreach: 'Robert HTN reminder + Kevin asthma refill - household batch',
        },
      ],
      caregiverFor: [
        {
          name: 'Mei Chen',
          relation: 'Mother',
          age: 88,
          condition: 'Post-stroke + hypertension',
          clinicalMetric: 'BP 158/92 - not at goal',
          pharmacy: 'Highland Pharmacy',
          prescriber: 'Summit Regional',
          meds: [
            { name: 'Amlodipine', dose: '10mg', indication: 'Hypertension' },
            { name: 'Atorvastatin', dose: '40mg', indication: 'Stroke prevention' },
            { name: 'Aspirin', dose: '81mg', indication: 'Antiplatelet' },
          ],
          consentScopeItems: [
            'Medication list',
            'Appointment scheduling',
            'Interpreter coordination (Mandarin)',
          ],
          consentExclusions: ['Behavioral health records', 'Third-party disclosure'],
        },
      ],
    },
    fhirId: 'patient/robert-chen-103',
    ehrMrn: 'MRN-0103',
    name: 'Robert Chen',
    age: 62,
    gender: 'M',
    dob: '1964-11-03',
    location: '847 Summit Street, Rapid City SD 57701',
    phone: '(605) 555-0334',
    pcp: 'Dr. Castillo',
    careManager: 'Sarah Johnson',
    careManagerInitials: 'SJ',
    organization: 'Summit Regional',
    contract: 'Medicaid RHTP Track 3',
    attribution: 'Confirmed · Medicaid RHTP Track 3',
    rafScore: 1.9,
    riskTier: 'High',
    riskLabel: 'High — 52% ER risk',
    erRiskPct: 52,
    hccSuspects: 2,
    hccValue: 11200,
    openCareGaps: 5,
    episodeType: 'Hypertension · CKD',
    episodeStatus: 'Active',
    episodeDaysActive: 156,
    pmpm: 980,
    pmpmTarget: 750,
    lastContact: '6 weeks ago',
    bhScreeningLabel: 'AUDIT-C',
    bhScore: 4,
    bhScoreLabel: 'AUDIT-C 4 — Low-moderate alcohol risk',
    auditC: 4,
    bhRisk: 'Low',
    bhReferralStatus: 'Not referred',
    bhProvider: '—',
    burdenScore: 'PAM 3 — Beginning to take action',
    patientGoal: "'Control my blood pressure and protect my kidneys'",
    transportStatus: 'Adequate — urban location',
    foodSecurity: 'No flag',
    housingStatus: 'Stable — rents apartment',
    language: 'English / Mandarin',
    ruralDistance: '5 miles to clinic',
    disparityFlag: 'Asian American · Medicaid',
    cohortFlag: 'Hypertension · CKD · Urban SD',
    snapStatus: 'Not enrolled',
    digitalAccess: 'Smartphone + broadband',
    careGaps: [
      {
        id: 'rc-1',
        domain: 'Clinical',
        name: 'BP Control Check',
        status: 'Open',
        daysOpen: 28,
        assignedTo: 'Dr. Castillo',
      },
      {
        id: 'rc-2',
        domain: 'Clinical',
        name: 'eGFR / Creatinine (CKD)',
        status: 'Open',
        daysOpen: 42,
        assignedTo: 'Dr. Castillo',
      },
      {
        id: 'rc-3',
        domain: 'Clinical',
        name: 'Urine Albumin-to-Creatinine Ratio',
        status: 'Open',
        daysOpen: 60,
        assignedTo: 'Dr. Castillo',
      },
      {
        id: 'rc-4',
        domain: 'BH',
        name: 'AUDIT-C Follow-up Counseling',
        status: 'Open',
        daysOpen: 21,
        assignedTo: 'Sarah Johnson',
      },
      {
        id: 'rc-5',
        domain: 'Social',
        name: 'Medication Cost Assistance',
        status: 'In Progress',
        daysOpen: 14,
        assignedTo: 'Sarah Johnson',
      },
    ],
    pathwaySteps: [
      {
        id: 'rcps-1',
        label: 'Hypertension Education',
        status: 'completed',
        date: 'Feb 10',
        metric: 'Completed',
      },
      {
        id: 'rcps-2',
        label: 'CKD Monitoring Protocol',
        status: 'completed',
        date: 'Mar 1',
        metric: 'Active',
      },
      {
        id: 'rcps-3',
        label: 'BP Control Optimization',
        status: 'in_progress',
        metric: 'Target: <130/80',
      },
      { id: 'rcps-4', label: 'Nephrology Referral', status: 'pending', metric: 'CKD Stage 3' },
      { id: 'rcps-5', label: 'AUDIT-C Counseling', status: 'pending', metric: 'Low-moderate risk' },
    ],
    aiCopilot:
      'Hypertension + CKD Stage 3 — BP control check 28 days overdue, eGFR 42 days overdue. AUDIT-C 4 low-moderate alcohol risk — counseling recommended. Medication cost assistance in progress. Consider nephrology referral given CKD progression risk.',
    cdsCards: [
      {
        id: 'cds-robert-1',
        indicator: 'warning',
        summary: 'BP control check overdue 28 days — hypertension gap',
        detail:
          'Blood pressure control check is 28 days overdue. Last reading 158/96. Target <130/80. CKD Stage 3 makes BP control critical for kidney protection.',
      },
      {
        id: 'cds-robert-2',
        indicator: 'warning',
        summary: 'eGFR overdue 42 days — CKD monitoring gap',
        detail:
          'CKD monitoring labs (eGFR, creatinine, UACR) are overdue. Last eGFR 42 (Stage 3b). Nephrology referral recommended if eGFR continues to decline.',
      },
      {
        id: 'cds-robert-3',
        indicator: 'info',
        summary: 'AUDIT-C 4 — low-moderate alcohol risk, counseling recommended',
        detail:
          'AUDIT-C score 4 indicates low-moderate alcohol use risk. Brief counseling recommended. Alcohol use can worsen hypertension and accelerate CKD progression.',
      },
    ],
    conditions: [
      {
        key: 'rc-c1',
        code: 'I10',
        name: 'Essential (primary) hypertension',
        onset: '2014-06',
        status: 'Active',
        source: 'EMR',
      },
      {
        key: 'rc-c2',
        code: 'N18.3',
        name: 'Chronic kidney disease, stage 3b',
        onset: '2020-10',
        status: 'Active',
        source: 'EMR',
      },
      {
        key: 'rc-c3',
        code: 'F10.10',
        name: 'Alcohol use disorder, mild',
        onset: '2023-05',
        status: 'Active',
        source: 'EMR',
      },
    ],
    medications: [
      {
        key: 'rc-m1',
        name: 'Amlodipine',
        dose: '10mg',
        frequency: 'Daily',
        prescriber: 'Dr. Castillo',
        lastFill: '2026-04-05',
        adherence: 0.87,
        ddi: false,
      },
      {
        key: 'rc-m2',
        name: 'Losartan',
        dose: '100mg',
        frequency: 'Daily',
        prescriber: 'Dr. Castillo',
        lastFill: '2026-04-05',
        adherence: 0.81,
        ddi: false,
      },
      {
        key: 'rc-m3',
        name: 'Atorvastatin',
        dose: '40mg',
        frequency: 'Nightly',
        prescriber: 'Dr. Castillo',
        lastFill: '2026-03-22',
        adherence: 0.79,
        ddi: false,
      },
    ],
    recentOrders: [
      {
        key: 'rc-o1',
        type: 'Lab',
        name: 'BP Check',
        result: '158/96 mmHg',
        date: '2026-03-15',
        status: 'Resulted',
        flag: 'High',
      },
      {
        key: 'rc-o2',
        type: 'Lab',
        name: 'eGFR / Creatinine',
        result: 'eGFR 42 (Stage 3b)',
        date: '2026-02-28',
        status: 'Resulted',
        flag: 'Low',
      },
      {
        key: 'rc-o3',
        type: 'Lab',
        name: 'Urine UACR',
        result: 'Overdue 60 days',
        date: '2026-02-15',
        status: 'Ordered',
        flag: 'High',
      },
      {
        key: 'rc-o4',
        type: 'Referral',
        name: 'Nephrology',
        result: 'Pending referral',
        date: '2026-04-10',
        status: 'Pending',
        flag: null,
      },
    ],
    carePlanDomains: [
      {
        domain: 'Clinical',
        color: '#0043ce',
        icon: 'HeartIcon',
        goals: [
          {
            goal: 'BP < 130/80 by Q3 2026',
            status: 'in-progress',
            owner: 'Dr. Castillo',
            dueDate: '2026-09-30',
            tasks: [
              'Amlodipine 10mg + Losartan 100mg continued',
              'Home BP log weekly',
              'Sodium-restricted diet counseling',
            ],
          },
          {
            goal: 'eGFR stabilized ≥ 40 by Q4 2026',
            status: 'in-progress',
            owner: 'Dr. Castillo',
            dueDate: '2026-12-31',
            tasks: [
              'Quarterly eGFR monitoring',
              'UACR lab ordered',
              'Nephrology referral if eGFR < 35',
            ],
          },
        ],
      },
      {
        domain: 'Behavioral Health',
        color: '#6929c4',
        icon: 'SparklesIcon',
        goals: [
          {
            goal: 'AUDIT-C counseling completed',
            status: 'open',
            owner: 'Sarah Johnson',
            dueDate: '2026-06-30',
            tasks: ['Brief alcohol intervention session', 'Follow-up AUDIT-C in 3 months'],
          },
        ],
      },
      {
        domain: 'Social Needs',
        color: '#b45309',
        icon: 'HomeIcon',
        goals: [
          {
            goal: 'Medication cost assistance enrolled',
            status: 'in-progress',
            owner: 'Sarah Johnson',
            dueDate: '2026-05-31',
            tasks: [
              'Patient Assistance Program application submitted',
              'Pharmacy discount card provided',
            ],
          },
        ],
      },
    ],
  },
];
