// patientRegistry.data1.ts — FHIR ID maps + Maria Redhawk + Dorothy Simmons
import type { RegistryPatient } from './patientRegistry.types';

// ─── FHIR ID Mapping Table ────────────────────────────────────────────────────
export const FHIR_ID_MAP: Record<string, string> = {
  'patient/maria-redhawk-001': 'MARIA_SD_001',
  'patient-maria-001': 'MARIA_SD_001',
  'patient/dorothy-simmons-042': 'PAT-0042',
  'patient-dorothy-042': 'PAT-0042',
  'patient/james-wilson-087': 'PAT-0087',
  'patient-james-087': 'PAT-0087',
  'patient/robert-chen-103': 'PAT-0103',
  'patient-robert-103': 'PAT-0103',
  'patient/lisa-thompson-156': 'PAT-0156',
  'patient-lisa-156': 'PAT-0156',
  'patient/alex-kirby': 'PAT-0200',
  'patient-alex-kirby': 'PAT-0200',
  'patient-001': 'PAT-0042',
  'patient-002': 'PAT-0087',
  'patient-003': 'PAT-0103',
  'patient-004': 'PAT-0156',
};

export const PLATFORM_TO_FHIR_ID_MAP: Record<string, string> = {
  MARIA_SD_001: 'patient-maria-001',
  'PAT-0042': 'patient-dorothy-042',
  'PAT-0087': 'patient-james-087',
  'PAT-0103': 'patient-robert-103',
  'PAT-0156': 'patient-lisa-156',
  'PAT-0200': 'patient-alex-kirby',
};

// ─── Patient Data: Maria Redhawk + Dorothy Simmons ───────────────────────────
export const REGISTRY_PART1: RegistryPatient[] = [
  // ── Maria Redhawk — Mock Data Only (always visible, never reads FHIR) ────────
  {
    mockOnly: true,
    platformId: 'MARIA_SD_001',
    journey: { id: 'POSTPARTUM_90D', currentDay: 34 },
    household: {
      dependents: [
        {
          name: 'Sophia Redhawk',
          relation: 'Daughter',
          age: 2,
          dob: 'June 2024',
          plan: 'SD CHIP',
          consent: 'Parent proxy - ACTIVE',
          gaps: [
            {
              label: 'Well-Child 24-Month Visit',
              urgency: 'high',
              detail: '21 days overdue - transportation barrier (47 mi)',
            },
            {
              label: 'Immunizations (DTaP, MMR)',
              urgency: 'due',
              detail: 'Bundle with well-child visit',
            },
          ],
          coordinatedOutreach:
            'Maria postpartum check-in + Sophia well-child - one SMS, one outreach',
        },
      ],
      caregiverFor: [
        {
          name: 'Elena Redhawk',
          relation: 'Mother',
          age: 66,
          condition: 'Heart disease + Type 2 diabetes',
          clinicalMetric: 'A1C 8.1% - DM management',
          pharmacy: 'Martin Pharmacy',
          prescriber: 'Bennett County Health',
          meds: [
            { name: 'Metformin', dose: '1000mg', indication: 'Type 2 Diabetes' },
            { name: 'Lisinopril', dose: '10mg', indication: 'Hypertension' },
          ],
          consentScopeItems: ['Medication list', 'Appointment scheduling', 'Refill coordination'],
          consentExclusions: ['Behavioral health records', 'Third-party disclosure'],
        },
      ],
    },
    fhirId: 'patient/maria-redhawk-001',
    ehrMrn: 'MARIA_SD_001',
    name: 'Maria Redhawk',
    age: 34,
    gender: 'F',
    dob: '1992-06-15',
    location: 'Martin, SD 57551',
    phone: '(605) 555-0234',
    pcp: 'Bennett County Health',
    careManager: 'Sarah Johnson',
    careManagerInitials: 'SJ',
    organization: 'Bennett County Health (CAH)',
    contract: 'SD Medicaid',
    attribution: 'Confirmed',
    rafScore: 2.18,
    riskTier: 'Moderate',
    riskLabel: 'Moderate — Pre-diabetic',
    erRiskPct: 42,
    hccSuspects: 3,
    hccValue: 12400,
    openCareGaps: 9,
    episodeType: 'Postpartum Health',
    episodeStatus: 'Active',
    episodeDaysActive: 427,
    pmpm: 1240,
    pmpmTarget: 780,
    lastContact: 'May 1, 2026',
    bhScreeningLabel: 'Edinburgh PND',
    bhScore: 11,
    bhScoreLabel: 'Edinburgh PND 11 — Moderate Postpartum Depression',
    auditC: 0,
    bhRisk: 'Moderate',
    bhReferralStatus: 'Referred (May 1, 2026)',
    bhProvider: 'Postpartum Support Group',
    burdenScore: 'PAM Score: 2 - Building Knowledge',
    patientGoal: "'Manage my health while caring for Sophia and Elena'",
    transportStatus: 'High Barrier — 47 miles to Winner Regional',
    foodSecurity: 'Moderate Insecurity — SNAP active, WIC expired',
    housingStatus: 'Rental Assistance Waitlist (Position 47)',
    language: 'English',
    ruralDistance: '47 miles to Winner Regional Healthcare',
    disparityFlag: 'Transportation · Childcare · Digital Divide',
    cohortFlag: 'Rural · Single Parent · Caregiver',
    snapStatus: 'SNAP active · WIC expired (May 1, 2025)',
    digitalAccess: 'Moderate Literacy',
    careGaps: [
      {
        id: 'mg-1',
        domain: 'Clinical',
        name: 'HbA1c Lab',
        status: 'Open',
        daysOpen: 38,
        assignedTo: 'Bennett County Health',
      },
      {
        id: 'mg-2',
        domain: 'Clinical',
        name: 'Edinburgh PND Screening',
        status: 'Open',
        daysOpen: 427,
        assignedTo: 'Sarah Johnson (Care Manager)',
      },
      {
        id: 'mg-3',
        domain: 'Clinical',
        name: 'Well-Child 24-Month Visit (Sophia)',
        status: 'Open',
        daysOpen: 21,
        assignedTo: 'Bennett County Health',
      },
      {
        id: 'mg-4',
        domain: 'BH',
        name: 'Postpartum Depression Follow-up',
        status: 'In Progress',
        daysOpen: 427,
        assignedTo: 'Postpartum Support Group',
      },
      {
        id: 'mg-5',
        domain: 'BH',
        name: 'Caregiver Burden Assessment',
        status: 'Open',
        daysOpen: 90,
        assignedTo: 'Sarah Johnson (Care Manager)',
      },
      {
        id: 'mg-6',
        domain: 'Social',
        name: 'Transportation Barrier Resolution',
        status: 'In Progress',
        daysOpen: 38,
        assignedTo: 'Sarah Johnson',
      },
      {
        id: 'mg-7',
        domain: 'Social',
        name: 'Childcare Subsidy Enrollment',
        status: 'Open',
        daysOpen: 60,
        assignedTo: 'Sarah Johnson',
      },
      {
        id: 'mg-8',
        domain: 'Social',
        name: 'WIC Re-enrollment',
        status: 'Open',
        daysOpen: 45,
        assignedTo: 'Sarah Johnson',
      },
      {
        id: 'mg-9',
        domain: 'Social',
        name: 'LIHEAP Application (Utility Assistance)',
        status: 'Open',
        daysOpen: 30,
        assignedTo: 'Sarah Johnson',
      },
    ],
    pathwaySteps: [
      {
        id: 'mps-1',
        label: 'PRAPARE Screening',
        status: 'completed',
        date: 'May 1, 2026',
        metric: '7 domains unmet',
      },
      {
        id: 'mps-2',
        label: 'Edinburgh PND Screening',
        status: 'completed',
        date: 'May 1, 2026',
        metric: 'Score 11 (Moderate)',
      },
      {
        id: 'mps-3',
        label: 'Childcare Subsidy Enrollment',
        status: 'in_progress',
        date: 'In progress',
        metric: '$487/month eligible',
      },
      {
        id: 'mps-4',
        label: 'HbA1c Lab Completion',
        status: 'pending',
        date: 'Due June 22, 2026',
        metric: 'Last: 6.2% (Pre-diabetic)',
      },
      { id: 'mps-5', label: 'WIC Re-enrollment', status: 'pending', metric: '$320/month benefit' },
    ],
    aiCopilot:
      'Transportation barrier (47 miles) is primary blocker affecting all clinical appointments. Postpartum depression (Edinburgh PND 11) untreated for 427 days - BH referral sent May 1 but not yet enrolled. Childcare subsidy ($487/mo) critical for appointment attendance. Pre-diabetes monitoring (HbA1c 6.2%) overdue. Multiple eligible benefits not enrolled: WIC ($320/mo), LIHEAP, Medicaid transport. Single parent with 2 young children (Sophia 24mo, Elena infant). Care Manager: Sarah Johnson.',
    cdsCards: [
      {
        id: 'cds-maria-1',
        indicator: 'critical',
        summary: 'Edinburgh PND overdue 427 days — postpartum depression untreated',
        detail:
          'Postpartum depression screening shows Edinburgh PND score 11 (Moderate). Patient is 427 days postpartum with untreated moderate depression. BH referral sent May 1, 2026 to Postpartum Support Group — patient not yet enrolled. Immediate follow-up required for maternal mental health.',
      },
      {
        id: 'cds-maria-2',
        indicator: 'warning',
        summary: 'HbA1c gap 38 days — pre-diabetes monitoring critical',
        detail:
          'Pre-diabetic HbA1c recheck is 38 days overdue. Last HbA1c: 6.2% (Pre-diabetic range). Due date: June 22, 2026. Primary barrier: 47-mile distance to Winner Regional Healthcare with no reliable transport. Consider NEMT enrollment and bundle with Well-Child visit.',
      },
      {
        id: 'cds-maria-3',
        indicator: 'warning',
        summary: 'Well-Child 24-month visit — Sophia overdue 21 days',
        detail:
          "Daughter Sophia's 24-month well-child visit is 21 days overdue. Transportation barrier (47 miles) preventing appointment attendance. Bundle with Maria's HbA1c lab to reduce trips. Childcare coordination needed.",
      },
      {
        id: 'cds-maria-4',
        indicator: 'info',
        summary: 'Multiple eligible benefits not enrolled — $807/month total',
        detail:
          'Maria is eligible for multiple benefits not currently enrolled: Childcare Subsidy ($487/mo), WIC Re-enrollment ($320/mo), LIHEAP (utility assistance), and Medicaid Non-Emergency Transport. Total monthly benefit value: $807. Enrollment would significantly improve care access and financial stability.',
      },
    ],
    conditions: [
      {
        key: 'mar-c1',
        code: 'O90.6',
        name: 'Postpartum mood disturbance',
        onset: '2025-07',
        status: 'Active',
        source: 'EMR',
      },
      {
        key: 'mar-c2',
        code: 'R73.09',
        name: 'Pre-diabetes (HbA1c 6.2%)',
        onset: '2024-11',
        status: 'Active',
        source: 'EMR',
      },
      {
        key: 'mar-c3',
        code: 'Z62.89',
        name: 'Caregiver stress — mother + infant',
        onset: '2025-06',
        status: 'Active',
        source: 'EMR',
      },
    ],
    medications: [
      {
        key: 'mar-m1',
        name: 'Prenatal Vitamin',
        dose: '1 tab',
        frequency: 'Daily',
        prescriber: 'Bennett County Health',
        lastFill: '2026-04-15',
        adherence: 0.88,
        ddi: false,
      },
      {
        key: 'mar-m2',
        name: 'Sertraline',
        dose: '25mg',
        frequency: 'Daily',
        prescriber: 'Bennett County Health',
        lastFill: '2026-05-01',
        adherence: 0.72,
        ddi: false,
      },
    ],
    recentOrders: [
      {
        key: 'mar-o1',
        type: 'Lab',
        name: 'HbA1c',
        result: '6.2% (Pre-diabetic)',
        date: '2025-12-10',
        status: 'Resulted',
        flag: 'High',
      },
      {
        key: 'mar-o2',
        type: 'Screening',
        name: 'Edinburgh PND',
        result: 'Score 11 (Moderate)',
        date: '2026-05-01',
        status: 'Resulted',
        flag: 'High',
      },
      {
        key: 'mar-o3',
        type: 'Referral',
        name: 'Postpartum Support Group',
        result: 'Awaiting enrollment',
        date: '2026-05-01',
        status: 'Pending',
        flag: null,
      },
      {
        key: 'mar-o4',
        type: 'Well-Child',
        name: 'Sophia 24-Month Visit',
        result: 'Overdue 21 days',
        date: '2026-04-10',
        status: 'Ordered',
        flag: 'High',
      },
    ],
    carePlanDomains: [
      {
        domain: 'Clinical',
        color: '#0043ce',
        icon: 'HeartIcon',
        goals: [
          {
            goal: 'HbA1c recheck by June 22, 2026',
            status: 'open',
            owner: 'Bennett County Health',
            dueDate: '2026-06-22',
            tasks: [
              'NEMT enrollment for lab visit',
              'Bundle with Sophia well-child',
              'HbA1c result review with PCP',
            ],
          },
        ],
      },
      {
        domain: 'Behavioral Health',
        color: '#6929c4',
        icon: 'SparklesIcon',
        goals: [
          {
            goal: 'Edinburgh PND score < 7 by Q4 2026',
            status: 'in-progress',
            owner: 'Postpartum Support Group',
            dueDate: '2026-10-31',
            tasks: [
              'Enroll in Postpartum Support Group',
              'Weekly BH check-in',
              'Sertraline titration review',
            ],
          },
          {
            goal: 'Caregiver burden assessment completed',
            status: 'open',
            owner: 'Sarah Johnson',
            dueDate: '2026-06-30',
            tasks: ['Schedule PAM assessment', 'Refer to respite care resources'],
          },
        ],
      },
      {
        domain: 'Social Needs',
        color: '#b45309',
        icon: 'HomeIcon',
        goals: [
          {
            goal: 'Transportation barrier resolved by Q3 2026',
            status: 'in-progress',
            owner: 'Sarah Johnson',
            dueDate: '2026-09-30',
            tasks: ['Medicaid NEMT benefit activated', 'Rideshare coordination for appointments'],
          },
          {
            goal: 'Childcare subsidy enrolled by Jun 2026',
            status: 'open',
            owner: 'Sarah Johnson',
            dueDate: '2026-06-30',
            tasks: ['Complete DHS childcare application', 'Submit income verification'],
          },
          {
            goal: 'WIC re-enrollment by Jul 2026',
            status: 'open',
            owner: 'Sarah Johnson',
            dueDate: '2026-07-31',
            tasks: ['Schedule WIC office appointment', 'Gather household income documents'],
          },
        ],
      },
    ],
  },

  // ── Dorothy Simmons ──────────────────────────────────────────────────────────
  {
    platformId: 'PAT-0042',
    journey: { id: 'COPD_30D', currentDay: 14 },
    household: {
      dependents: [],
      caregiverFor: [
        {
          name: 'Earl Simmons',
          relation: 'Husband',
          age: 78,
          condition: 'Vascular dementia + hypertension',
          clinicalMetric: 'BP 146/88 - borderline',
          pharmacy: 'Ozark Pharmacy',
          prescriber: 'Ozark Regional FQHC',
          meds: [
            { name: 'Donepezil', dose: '10mg', indication: 'Dementia' },
            { name: 'Lisinopril', dose: '20mg', indication: 'Hypertension' },
            { name: 'Amlodipine', dose: '5mg', indication: 'Hypertension' },
          ],
          consentScopeItems: ['Medication list', 'Appointment scheduling', 'Refill coordination'],
          consentExclusions: ['Behavioral health records', 'Third-party disclosure'],
        },
      ],
    },
    fhirId: 'patient/dorothy-simmons-042',
    ehrMrn: 'MRN-0042',
    name: 'Dorothy Simmons',
    age: 75,
    gender: 'F',
    dob: '1951-03-14',
    location: 'Ozark Regional FQHC Service Area',
    phone: '(417) 555-0198',
    pcp: 'Dr. Whitfield',
    careManager: 'Sarah Johnson',
    careManagerInitials: 'SJ',
    organization: 'Ozark Regional FQHC',
    contract: 'MSSP Trk 3',
    attribution: 'Confirmed · MSSP Trk 3',
    rafScore: 3.42,
    riskTier: 'Critical',
    riskLabel: 'Critical — 84% ER risk',
    erRiskPct: 84,
    hccSuspects: 4,
    hccValue: 24800,
    openCareGaps: 11,
    episodeType: 'COPD Exacerbation',
    episodeStatus: 'Active',
    episodeDaysActive: 14,
    pmpm: 2840,
    pmpmTarget: 890,
    lastContact: 'Mar 28, 2026',
    bhScreeningLabel: 'PHQ-9',
    bhScore: 14,
    bhScoreLabel: 'PHQ-9 14 — Moderate depression',
    auditC: 2,
    bhRisk: 'Moderate',
    bhReferralStatus: 'Open — referred Mar 15',
    bhProvider: 'Cascade Valley BH',
    burdenScore: 'PAM 1 — Overwhelmed',
    patientGoal: "'Stay home with my family'",
    transportStatus: 'Active — Unite Us #TU-48821',
    foodSecurity: 'Screened — no flag',
    housingStatus: 'Stable',
    language: 'English',
    ruralDistance: '38 miles to FQHC',
    disparityFlag: 'None identified',
    cohortFlag: 'Ag worker · Seasonal flag',
    snapStatus: 'Active',
    digitalAccess: 'Limited — phone only',
    careGaps: [
      {
        id: 'gap-1',
        domain: 'Clinical',
        name: 'Spirometry (COPD)',
        status: 'Open',
        daysOpen: 42,
        assignedTo: 'Dr. Whitfield',
      },
      {
        id: 'gap-2',
        domain: 'Clinical',
        name: 'Flu Vaccine',
        status: 'In Progress',
        daysOpen: 18,
        assignedTo: 'Sarah Johnson',
      },
      {
        id: 'gap-3',
        domain: 'Clinical',
        name: 'Medication Reconciliation',
        status: 'Open',
        daysOpen: 14,
        assignedTo: 'Sarah Johnson',
      },
      {
        id: 'gap-4',
        domain: 'Clinical',
        name: 'A1C Recheck',
        status: 'Open',
        daysOpen: 61,
        assignedTo: 'Dr. Whitfield',
      },
      {
        id: 'gap-5',
        domain: 'Clinical',
        name: 'Retinal Exam',
        status: 'Open',
        daysOpen: 90,
        assignedTo: 'Dr. Whitfield',
      },
      {
        id: 'gap-6',
        domain: 'Clinical',
        name: 'Nephropathy Screening',
        status: 'Open',
        daysOpen: 30,
        assignedTo: 'Dr. Whitfield',
      },
      {
        id: 'gap-7',
        domain: 'BH',
        name: 'PHQ-9 Follow-up',
        status: 'In Progress',
        daysOpen: 21,
        assignedTo: 'Cascade Valley BH',
      },
      {
        id: 'gap-8',
        domain: 'BH',
        name: 'Trauma Screening (ACE)',
        status: 'Open',
        daysOpen: 45,
        assignedTo: 'Sarah Johnson',
      },
      {
        id: 'gap-9',
        domain: 'Social',
        name: 'Transport Referral — Active',
        status: 'In Progress',
        daysOpen: 18,
        assignedTo: 'Maria Gonzalez',
      },
      {
        id: 'gap-10',
        domain: 'Social',
        name: 'Housing Stability Plan',
        status: 'Open',
        daysOpen: 33,
        assignedTo: 'Maria Gonzalez',
      },
      {
        id: 'gap-11',
        domain: 'Social',
        name: 'SNAP Re-certification',
        status: 'Open',
        daysOpen: 12,
        assignedTo: 'Maria Gonzalez',
      },
    ],
    pathwaySteps: [
      {
        id: 'ps-1',
        label: 'Food Insecurity Screening',
        status: 'completed',
        date: 'Jan 8',
        metric: 'SNAP enrolled',
      },
      {
        id: 'ps-2',
        label: 'SNAP Enrollment',
        status: 'completed',
        date: 'Feb 2',
        metric: 'Active',
      },
      {
        id: 'ps-3',
        label: 'BH Engagement',
        status: 'in_progress',
        date: 'Mar 15',
        metric: 'PHQ-9 14',
      },
      { id: 'ps-4', label: 'A1C Recheck', status: 'in_progress', metric: 'Goal: <7.0%' },
      { id: 'ps-5', label: 'Medication Reconciliation', status: 'pending', metric: 'COPD regimen' },
    ],
    aiCopilot:
      'PHQ-9 14 — BH referral open since Mar 15, not yet engaged. COPD exacerbation active — spirometry overdue 42 days. RAF 3.42 with 4 HCC suspects ($24,800 value). A1C 9.2% — diabetes poorly controlled. Priority: BH engagement + medication reconciliation this week.',
    cdsCards: [
      {
        id: 'cds-dorothy-1',
        indicator: 'critical',
        summary: 'PHQ-9 14 — BH referral open since Mar 15, not engaged',
        detail:
          'Moderate depression (PHQ-9 14). BH referral to Cascade Valley BH sent Mar 15 — patient has not engaged. Immediate outreach required. FUH/FUM measure at risk.',
      },
      {
        id: 'cds-dorothy-2',
        indicator: 'warning',
        summary: 'COPD Exacerbation — spirometry overdue 42 days',
        detail:
          'Active COPD exacerbation episode. Spirometry not completed in 42 days. Medication reconciliation also overdue. Follow-up within 7 days required per care plan.',
      },
      {
        id: 'cds-dorothy-3',
        indicator: 'info',
        summary: 'RAF 3.42 — 4 HCC suspects, $24,800 revenue at risk',
        detail:
          '4 HCC suspects identified: T2DM with CKD Stage 3, COPD, Major Depression, Cardiac. Documentation deadline Dec 31, 2026. Estimated RAF delta: +0.42 if all captured.',
      },
      {
        id: 'cds-dorothy-4',
        indicator: 'warning',
        summary: 'A1C 9.2% — diabetes poorly controlled',
        detail:
          'Last A1C 9.2% (Feb 10). Target <7.0%. Retinal exam and nephropathy screening both overdue. Consider endocrinology referral given CKD Stage 3b (eGFR 42).',
      },
    ],
    conditions: [
      {
        key: 'dot-c1',
        code: 'I50.32',
        name: 'Chronic diastolic heart failure',
        onset: '2019-03',
        status: 'Active',
        source: 'EMR',
      },
      {
        key: 'dot-c2',
        code: 'E11.65',
        name: 'Type 2 diabetes mellitus with hyperglycemia',
        onset: '2014-07',
        status: 'Active',
        source: 'EMR',
      },
      {
        key: 'dot-c3',
        code: 'J44.1',
        name: 'COPD with acute exacerbation',
        onset: '2021-11',
        status: 'Active',
        source: 'HIE',
      },
      {
        key: 'dot-c4',
        code: 'I10',
        name: 'Essential (primary) hypertension',
        onset: '2012-03',
        status: 'Active',
        source: 'EMR',
      },
      {
        key: 'dot-c5',
        code: 'E66.01',
        name: 'Morbid obesity due to excess calories',
        onset: '2016-05',
        status: 'Active',
        source: 'EMR',
      },
      {
        key: 'dot-c6',
        code: 'N18.3',
        name: 'Chronic kidney disease, stage 3',
        onset: '2022-09',
        status: 'Active',
        source: 'Claims',
      },
      {
        key: 'dot-c7',
        code: 'F32.1',
        name: 'Major depressive disorder, single episode',
        onset: '2023-02',
        status: 'Active',
        source: 'EMR',
      },
    ],
    medications: [
      {
        key: 'dot-m1',
        name: 'Furosemide',
        dose: '40mg',
        frequency: 'Daily',
        prescriber: 'Dr. Whitfield',
        lastFill: '2026-04-01',
        adherence: 0.92,
        ddi: false,
      },
      {
        key: 'dot-m2',
        name: 'Metformin HCl',
        dose: '1000mg',
        frequency: 'BID',
        prescriber: 'Dr. Whitfield',
        lastFill: '2026-03-28',
        adherence: 0.71,
        ddi: false,
      },
      {
        key: 'dot-m3',
        name: 'Warfarin Sodium',
        dose: '5mg',
        frequency: 'Daily',
        prescriber: 'Dr. Whitfield',
        lastFill: '2026-04-08',
        adherence: 0.95,
        ddi: true,
      },
      {
        key: 'dot-m4',
        name: 'Tiotropium bromide',
        dose: '18mcg',
        frequency: 'Daily inhaled',
        prescriber: 'Dr. Nakamura',
        lastFill: '2026-03-15',
        adherence: 0.68,
        ddi: false,
      },
      {
        key: 'dot-m5',
        name: 'Lisinopril',
        dose: '20mg',
        frequency: 'Daily',
        prescriber: 'Dr. Whitfield',
        lastFill: '2026-04-01',
        adherence: 0.89,
        ddi: false,
      },
      {
        key: 'dot-m6',
        name: 'Atorvastatin',
        dose: '40mg',
        frequency: 'Nightly',
        prescriber: 'Dr. Whitfield',
        lastFill: '2026-03-20',
        adherence: 0.84,
        ddi: false,
      },
      {
        key: 'dot-m7',
        name: 'Ibuprofen OTC',
        dose: '400mg',
        frequency: 'PRN',
        prescriber: 'OTC',
        lastFill: '2026-04-10',
        adherence: null,
        ddi: true,
      },
    ],
    recentOrders: [
      {
        key: 'dot-o1',
        type: 'Lab',
        name: 'HbA1c',
        result: '9.2%',
        date: '2026-03-15',
        status: 'Resulted',
        flag: 'High',
      },
      {
        key: 'dot-o2',
        type: 'Lab',
        name: 'BNP',
        result: '842 pg/mL',
        date: '2026-03-28',
        status: 'Resulted',
        flag: 'Critical',
      },
      {
        key: 'dot-o3',
        type: 'Imaging',
        name: 'Cardiac MRI',
        result: 'Pending',
        date: '2026-04-14',
        status: 'Ordered',
        flag: null,
      },
      {
        key: 'dot-o4',
        type: 'Referral',
        name: 'Ophthalmology',
        result: 'Awaiting scheduling',
        date: '2026-02-14',
        status: 'Pending',
        flag: null,
      },
      {
        key: 'dot-o5',
        type: 'Lab',
        name: 'eGFR / BMP',
        result: '38 mL/min',
        date: '2026-03-15',
        status: 'Resulted',
        flag: 'Low',
      },
      {
        key: 'dot-o6',
        type: 'Procedure',
        name: 'Echocardiogram',
        result: 'EF 35%',
        date: '2026-03-12',
        status: 'Resulted',
        flag: 'Low',
      },
    ],
    carePlanDomains: [
      {
        domain: 'Clinical',
        color: '#0043ce',
        icon: 'HeartIcon',
        goals: [
          {
            goal: 'A1C < 8.0 by Q3 2026',
            status: 'in-progress',
            owner: 'Dr. Whitfield',
            dueDate: '2026-09-30',
            tasks: ['Metformin titration', 'Diabetes education referral', 'A1C recheck in 90 days'],
          },
          {
            goal: 'BP < 130/80 by Q2 2026',
            status: 'open',
            owner: 'Dr. Whitfield',
            dueDate: '2026-06-30',
            tasks: ['Lisinopril 20mg titration', 'Home BP monitoring kit ordered'],
          },
          {
            goal: 'Spirometry completed by May 2026',
            status: 'open',
            owner: 'Dr. Whitfield',
            dueDate: '2026-05-31',
            tasks: ['Schedule spirometry at Ozark FQHC', 'COPD action plan update'],
          },
        ],
      },
      {
        domain: 'Behavioral Health',
        color: '#6929c4',
        icon: 'SparklesIcon',
        goals: [
          {
            goal: 'PHQ-9 score < 10 by Q3 2026',
            status: 'in-progress',
            owner: 'Cascade Valley BH',
            dueDate: '2026-09-30',
            tasks: [
              'Weekly BH counseling sessions',
              'Antidepressant medication review',
              'Safety plan documented',
            ],
          },
        ],
      },
      {
        domain: 'Social Needs',
        color: '#b45309',
        icon: 'HomeIcon',
        goals: [
          {
            goal: 'Transport referral active by May 2026',
            status: 'completed',
            owner: 'Maria Gonzalez',
            dueDate: '2026-05-31',
            tasks: ['Unite Us TU-48821 activated', 'Transport coordinator assigned'],
          },
          {
            goal: 'SNAP re-certification by Jun 2026',
            status: 'open',
            owner: 'Maria Gonzalez',
            dueDate: '2026-06-30',
            tasks: ['Recertification paperwork submitted', 'DHS appointment confirmed'],
          },
        ],
      },
    ],
  },
];
