// patientRegistry.data3.ts — Lisa Thompson
import type { RegistryPatient } from './patientRegistry.types';

export const REGISTRY_PART3: RegistryPatient[] = [
  // ── Lisa Thompson ─────────────────────────────────────────────────────────
  {
    platformId: 'PAT-0156',
    journey: { id: 'ASTHMA_OBESITY_365D', currentDay: 203 },
    household: {
      dependents: [
        {
          name: 'Mason Thompson',
          relation: 'Son',
          age: 7,
          dob: '2018',
          plan: 'CHIP',
          consent: 'Parent proxy - ACTIVE',
          gaps: [
            {
              label: 'Asthma Well-Child + Inhaler Technique',
              urgency: 'high',
              detail: 'Spacer technique review overdue',
            },
            {
              label: 'Immunizations (7-year catch-up)',
              urgency: 'due',
              detail: 'Catch-up DTaP / IPV',
            },
          ],
          coordinatedOutreach: 'Lisa asthma + Mason asthma - combined family asthma-action review',
        },
        {
          name: 'Ava Thompson',
          relation: 'Daughter',
          age: 4,
          dob: '2021',
          plan: 'CHIP',
          consent: 'Parent proxy - ACTIVE',
          gaps: [
            {
              label: 'Well-Child 4-Year Visit',
              urgency: 'due',
              detail: 'Vision + dental screening due',
            },
          ],
        },
      ],
      caregiverFor: [],
    },
    fhirId: 'patient/lisa-thompson-156',
    ehrMrn: 'MRN-0156',
    name: 'Lisa Thompson',
    age: 41,
    gender: 'F',
    dob: '1985-05-19',
    location: '223 Pine Ave, Sioux Falls SD 57104',
    phone: '(605) 555-0412',
    pcp: 'Dr. Torres',
    careManager: 'Sarah Johnson',
    careManagerInitials: 'SJ',
    organization: 'Sioux Falls Community Health',
    contract: 'Medicaid RHTP Track 3',
    attribution: 'Confirmed · Medicaid RHTP Track 3',
    rafScore: 1.4,
    riskTier: 'Moderate',
    riskLabel: 'Moderate — 31% ER risk',
    erRiskPct: 31,
    hccSuspects: 1,
    hccValue: 5800,
    openCareGaps: 4,
    episodeType: 'Asthma · Obesity',
    episodeStatus: 'Active',
    episodeDaysActive: 203,
    pmpm: 620,
    pmpmTarget: 480,
    lastContact: '5 weeks ago',
    bhScreeningLabel: 'PHQ-9',
    bhScore: 6,
    bhScoreLabel: 'PHQ-9 6 — Minimal symptoms',
    auditC: 1,
    bhRisk: 'Low',
    bhReferralStatus: 'Not referred',
    bhProvider: '—',
    burdenScore: 'PAM 3 — Beginning to take action',
    patientGoal: "'Lose weight and breathe easier'",
    transportStatus: 'Adequate — urban location',
    foodSecurity: 'SNAP active',
    housingStatus: 'Stable — rents apartment',
    language: 'English',
    ruralDistance: '3 miles to clinic',
    disparityFlag: 'Low income · Medicaid',
    cohortFlag: 'Asthma · Obesity · Urban SD',
    snapStatus: 'Active',
    digitalAccess: 'Smartphone + broadband',
    careGaps: [
      {
        id: 'lt-1',
        domain: 'Clinical',
        name: 'Asthma Action Plan Update',
        status: 'Open',
        daysOpen: 35,
        assignedTo: 'Dr. Torres',
      },
      {
        id: 'lt-2',
        domain: 'Clinical',
        name: 'BMI / Weight Management Referral',
        status: 'In Progress',
        daysOpen: 60,
        assignedTo: 'Dr. Torres',
      },
      {
        id: 'lt-3',
        domain: 'BH',
        name: 'PHQ-9 Annual Screening',
        status: 'Open',
        daysOpen: 18,
        assignedTo: 'Sarah Johnson',
      },
      {
        id: 'lt-4',
        domain: 'Social',
        name: 'Nutrition Counseling Enrollment',
        status: 'Open',
        daysOpen: 45,
        assignedTo: 'Sarah Johnson',
      },
    ],
    pathwaySteps: [
      {
        id: 'ltps-1',
        label: 'Asthma Education',
        status: 'completed',
        date: 'Jan 20',
        metric: 'Completed',
      },
      {
        id: 'ltps-2',
        label: 'Inhaler Technique Review',
        status: 'completed',
        date: 'Feb 5',
        metric: 'Corrected',
      },
      {
        id: 'ltps-3',
        label: 'Weight Management Program',
        status: 'in_progress',
        metric: 'Goal: -15 lbs',
      },
      {
        id: 'ltps-4',
        label: 'Nutrition Counseling',
        status: 'pending',
        metric: 'SNAP-Ed eligible',
      },
      {
        id: 'ltps-5',
        label: 'Asthma Action Plan Update',
        status: 'pending',
        metric: 'Annual review',
      },
    ],
    aiCopilot:
      'Asthma + Obesity — action plan update 35 days overdue, weight management referral in progress. PHQ-9 6 minimal symptoms — annual screening due. Nutrition counseling enrollment pending (SNAP-Ed eligible). Good engagement potential — urban location, broadband access.',
    cdsCards: [
      {
        id: 'cds-lisa-1',
        indicator: 'info',
        summary: 'Asthma action plan update overdue 35 days',
        detail:
          'Annual asthma action plan review is 35 days overdue. Inhaler technique corrected Feb 5. Consider spirometry to assess current lung function and update rescue medication plan.',
      },
      {
        id: 'cds-lisa-2',
        indicator: 'info',
        summary: 'Weight management referral in progress — BMI elevated',
        detail:
          'BMI elevated — weight management referral active. Patient goal: -15 lbs. SNAP-Ed nutrition counseling eligible. Consider structured weight management program enrollment.',
      },
      {
        id: 'cds-lisa-3',
        indicator: 'info',
        summary: 'PHQ-9 annual screening due',
        detail:
          'Annual PHQ-9 depression screening is due. Last score 6 (minimal). Chronic disease burden (asthma + obesity) increases BH risk. Complete during next encounter.',
      },
    ],
    conditions: [
      {
        key: 'lt-c1',
        code: 'J45.50',
        name: 'Severe persistent asthma, uncomplicated',
        onset: '2012-03',
        status: 'Active',
        source: 'EMR',
      },
      {
        key: 'lt-c2',
        code: 'E66.9',
        name: 'Obesity, unspecified (BMI 38)',
        onset: '2018-09',
        status: 'Active',
        source: 'EMR',
      },
    ],
    medications: [
      {
        key: 'lt-m1',
        name: 'Fluticasone / Salmeterol',
        dose: '250/50mcg',
        frequency: 'BID inhaled',
        prescriber: 'Dr. Torres',
        lastFill: '2026-04-08',
        adherence: 0.76,
        ddi: false,
      },
      {
        key: 'lt-m2',
        name: 'Albuterol HFA',
        dose: '90mcg',
        frequency: 'PRN',
        prescriber: 'Dr. Torres',
        lastFill: '2026-04-12',
        adherence: null,
        ddi: false,
      },
      {
        key: 'lt-m3',
        name: 'Montelukast',
        dose: '10mg',
        frequency: 'Daily',
        prescriber: 'Dr. Torres',
        lastFill: '2026-03-30',
        adherence: 0.88,
        ddi: false,
      },
    ],
    recentOrders: [
      {
        key: 'lt-o1',
        type: 'Lab',
        name: 'Spirometry',
        result: 'Overdue 35 days',
        date: '2026-03-28',
        status: 'Ordered',
        flag: 'High',
      },
      {
        key: 'lt-o2',
        type: 'Referral',
        name: 'Weight Management Program',
        result: 'In progress — -4 lbs since referral',
        date: '2026-02-20',
        status: 'Pending',
        flag: null,
      },
      {
        key: 'lt-o3',
        type: 'Screening',
        name: 'PHQ-9 Annual',
        result: 'Due',
        date: '2026-04-15',
        status: 'Ordered',
        flag: null,
      },
      {
        key: 'lt-o4',
        type: 'Referral',
        name: 'Nutrition Counseling (SNAP-Ed)',
        result: 'Pending enrollment',
        date: '2026-04-01',
        status: 'Pending',
        flag: null,
      },
    ],
    carePlanDomains: [
      {
        domain: 'Clinical',
        color: '#0043ce',
        icon: 'HeartIcon',
        goals: [
          {
            goal: 'Asthma action plan updated by Jun 2026',
            status: 'open',
            owner: 'Dr. Torres',
            dueDate: '2026-06-30',
            tasks: [
              'Spirometry scheduled',
              'Inhaler technique re-evaluation',
              'Rescue medication plan updated',
            ],
          },
          {
            goal: 'BMI reduction -15 lbs by Q4 2026',
            status: 'in-progress',
            owner: 'Dr. Torres',
            dueDate: '2026-12-31',
            tasks: [
              'Weight management program enrolled',
              'Weekly weigh-in log',
              'SNAP-Ed nutrition counseling',
            ],
          },
        ],
      },
      {
        domain: 'Behavioral Health',
        color: '#6929c4',
        icon: 'SparklesIcon',
        goals: [
          {
            goal: 'PHQ-9 annual screening completed',
            status: 'open',
            owner: 'Sarah Johnson',
            dueDate: '2026-06-30',
            tasks: ['PHQ-9 assessment scheduled', 'Review results with PCP'],
          },
        ],
      },
      {
        domain: 'Social Needs',
        color: '#b45309',
        icon: 'HomeIcon',
        goals: [
          {
            goal: 'Nutrition counseling enrollment by Jul 2026',
            status: 'open',
            owner: 'Sarah Johnson',
            dueDate: '2026-07-31',
            tasks: ['SNAP-Ed program referral sent', 'Confirm enrollment with community partner'],
          },
        ],
      },
    ],
  },
];
