// patientContext.defaults.ts — Default patient states for Maria Redhawk and Dorothy Simmons

import type { PatientSharedState } from './patientContext.types';

// ─── Default Maria Redhawk State ──────────────────────────────────────────────

export const defaultMariaState: PatientSharedState = {
  patientId: 'MARIA_SD_001',
  name: 'Maria Redhawk',
  mrn: 'MRN-SD-001',
  age: 34,
  gender: 'F',
  dob: '1992-03-22',
  pcp: 'Bennett County Health PCP',
  careManager: 'Sarah Johnson',
  careManagerInitials: 'SJ',
  organization: 'Bennett County Health Services',
  attribution: 'Confirmed · Medicaid RHTP Track 3',

  episodeType: 'Pre-Diabetic / Postpartum',
  episodeStatus: 'Active',
  episodeDaysActive: 427,
  pmpm: 1240,
  pmpmTarget: 890,
  rafScore: 1.42,
  rafDelta: 0.12,
  riskTier: 'Moderate — 38% ER risk',
  erRiskPct: 38,
  hccSuspects: 2,
  hccValue: 8400,
  lastContact: 'May 28, 2026',
  attributionDetail: 'Confirmed · Medicaid RHTP Track 3',

  phq9Score: 12,
  phq9Trend: '↑ Edinburgh PND 427d unmanaged',
  auditC: 0,
  traumaFlag: false,
  bhRisk: 'Moderate',
  bhReferralStatus: 'Referred — not enrolled',
  bhReferralDate: 'Apr 15',
  bhProvider: 'Postpartum Support Group — Bennett County',
  pamScore: 2,
  pamLabel: 'Struggling',
  patientGoal: "'Take care of Sophia and get back on my feet'",

  transportStatus: 'Active',
  transportReferralId: 'Unite Us #TU-SD-48821',
  referralStatus: 'Active',
  referralDaysOpen: 12,
  foodSecurity: 'SNAP expired T+47d — unmet need',
  housingStatus: 'Waitlist #47 — SDHDA',
  language: 'English / Lakota',
  literacy: 'moderate',
  cohortFlag: 'Postpartum · Frontier SD · Oglala Lakota',
  ruralDistance: '47 miles to Bennett County Health',
  disparityFlag: 'AI/AN · Rural frontier · Medicaid',
  snapStatus: 'Expired — renewal overdue',

  careGaps: [
    {
      id: 'mg-1',
      domain: 'Clinical',
      name: 'A1C Recheck (Pre-Diabetic)',
      status: 'Open',
      daysOpen: 38,
      assignedTo: 'Bennett County Health PCP',
    },
    {
      id: 'mg-2',
      domain: 'Clinical',
      name: 'Postpartum Visit (427d overdue)',
      status: 'Open',
      daysOpen: 427,
      assignedTo: 'Bennett County Health PCP',
    },
    {
      id: 'mg-3',
      domain: 'Clinical',
      name: 'Well-Child 24mo — Sophia (21d overdue)',
      status: 'Open',
      daysOpen: 21,
      assignedTo: 'Bennett County Health PCP',
    },
    {
      id: 'mg-4',
      domain: 'BH',
      name: 'Edinburgh PND Screening (427d)',
      status: 'Open',
      daysOpen: 427,
      assignedTo: 'Sarah Johnson',
    },
    {
      id: 'mg-5',
      domain: 'BH',
      name: 'Postpartum Support Group Enrollment',
      status: 'In Progress',
      daysOpen: 14,
      assignedTo: 'Sarah Johnson',
    },
    {
      id: 'mg-6',
      domain: 'Social',
      name: 'SNAP Renewal (T+47d overdue)',
      status: 'Open',
      daysOpen: 47,
      assignedTo: 'Bennett County Action CBO',
    },
    {
      id: 'mg-7',
      domain: 'Social',
      name: 'WIC Enrollment (eligible — not enrolled)',
      status: 'Open',
      daysOpen: 60,
      assignedTo: 'Bennett County Action CBO',
    },
    {
      id: 'mg-8',
      domain: 'Social',
      name: 'Childcare Subsidy (CCAP) Enrollment',
      status: 'Open',
      daysOpen: 60,
      assignedTo: 'Bennett County Action CBO',
    },
    {
      id: 'mg-9',
      domain: 'Social',
      name: 'Housing Waitlist Follow-up (#47)',
      status: 'In Progress',
      daysOpen: 90,
      assignedTo: 'Sarah Johnson',
    },
  ],

  pathwaySteps: [
    {
      id: 'mps-1',
      label: 'PRAPARE Screening',
      completed: true,
      date: 'Apr 15',
      metric: '5 unmet needs',
    },
    {
      id: 'mps-2',
      label: 'Transport Referral',
      completed: true,
      date: 'Apr 18',
      metric: 'NEMT Active',
    },
    {
      id: 'mps-3',
      label: 'SNAP Renewal',
      completed: false,
      date: 'Overdue T+47d',
      metric: '$281/mo',
    },
    {
      id: 'mps-4',
      label: 'WIC + CCAP Enroll',
      completed: false,
      date: 'Pending',
      metric: '$807/mo value',
    },
    { id: 'mps-5', label: 'A1C Recheck', completed: false, metric: 'Goal: <6.5%' },
  ],

  riskLabel: 'Moderate — 38% ER risk',
  bhScore: 12,
  bhScoreLabel: 'Edinburgh PND 12 — Moderate Postpartum Depression',
  aiCopilot:
    'Transportation barrier (47 miles) is primary blocker. Edinburgh PND 12 untreated. Multiple eligible benefits not enrolled. Care Manager: Sarah Johnson.',

  crisisCount30d: 0,
  lastCrisisDate: null,
  activeCrisis: false,
};

// ─── Default Dorothy Simmons State ───────────────────────────────────────────

export const defaultDorothyState: PatientSharedState = {
  patientId: 'PAT-0042',
  name: 'Dorothy Simmons',
  mrn: 'MRN-0042',
  age: 75,
  gender: 'F',
  dob: '1951-03-14',
  pcp: 'Dr. Whitfield',
  careManager: 'Sarah Johnson',
  careManagerInitials: 'SJ',
  organization: 'Ozark Regional FQHC',
  attribution: 'Confirmed · MSSP Trk 3',

  episodeType: 'COPD Exacerbation',
  episodeStatus: 'Active',
  episodeDaysActive: 14,
  pmpm: 2840,
  pmpmTarget: 890,
  rafScore: 3.42,
  rafDelta: 0.18,
  riskTier: 'Critical — 84% ER risk',
  erRiskPct: 84,
  hccSuspects: 4,
  hccValue: 24800,
  lastContact: 'Mar 28, 2026',
  attributionDetail: 'Confirmed · MSSP Trk 3',

  phq9Score: 14,
  phq9Trend: '↑ from 10 (3 months ago)',
  auditC: 2,
  traumaFlag: false,
  bhRisk: 'Moderate',
  bhReferralStatus: 'Open',
  bhReferralDate: 'Mar 15',
  bhProvider: 'Cascade Valley BH',
  pamScore: 1,
  pamLabel: 'Overwhelmed',
  patientGoal: "'Stay home with my family'",

  transportStatus: 'Active',
  transportReferralId: 'Unite Us #TU-48821',
  referralStatus: 'Pending',
  referralDaysOpen: 18,
  foodSecurity: 'Screened — no flag',
  housingStatus: 'Stable',
  language: 'English',
  literacy: 'moderate',
  cohortFlag: 'Ag worker · Seasonal flag',
  ruralDistance: '38 miles to FQHC',
  disparityFlag: 'None identified',
  snapStatus: 'Active',

  careGaps: [
    {
      id: 'gap-1',
      domain: 'Clinical',
      name: 'Spirometry (COPD)',
      status: 'Open',
      daysOpen: 42,
      assignedTo: 'Dr. Whitfield',
    },
    {
      id: 'gap-2',
      domain: 'Clinical',
      name: 'Flu Vaccine',
      status: 'In Progress',
      daysOpen: 18,
      assignedTo: 'Sarah Johnson',
    },
    {
      id: 'gap-3',
      domain: 'Clinical',
      name: 'Medication Reconciliation',
      status: 'Open',
      daysOpen: 14,
      assignedTo: 'Sarah Johnson',
    },
    {
      id: 'gap-4',
      domain: 'Clinical',
      name: 'A1C Recheck',
      status: 'Open',
      daysOpen: 61,
      assignedTo: 'Dr. Whitfield',
    },
    {
      id: 'gap-5',
      domain: 'Clinical',
      name: 'Retinal Exam',
      status: 'Open',
      daysOpen: 90,
      assignedTo: 'Dr. Whitfield',
    },
    {
      id: 'gap-6',
      domain: 'Clinical',
      name: 'Nephropathy Screening',
      status: 'Open',
      daysOpen: 30,
      assignedTo: 'Dr. Whitfield',
    },
    {
      id: 'gap-7',
      domain: 'BH',
      name: 'PHQ-9 Follow-up',
      status: 'In Progress',
      daysOpen: 21,
      assignedTo: 'Cascade Valley BH',
    },
    {
      id: 'gap-8',
      domain: 'BH',
      name: 'Trauma Screening (ACE)',
      status: 'Open',
      daysOpen: 45,
      assignedTo: 'Sarah Johnson',
    },
    {
      id: 'gap-9',
      domain: 'Social',
      name: 'Transport Referral — Active',
      status: 'In Progress',
      daysOpen: 18,
      assignedTo: 'Maria Gonzalez',
    },
    {
      id: 'gap-10',
      domain: 'Social',
      name: 'Housing Stability Plan',
      status: 'Open',
      daysOpen: 33,
      assignedTo: 'Maria Gonzalez',
    },
    {
      id: 'gap-11',
      domain: 'Social',
      name: 'SNAP Re-certification',
      status: 'Open',
      daysOpen: 12,
      assignedTo: 'Maria Gonzalez',
    },
  ],

  pathwaySteps: [
    {
      id: 'ps-1',
      label: 'Food Insecurity Screening',
      completed: true,
      date: 'Jan 8',
      metric: 'SNAP enrolled',
    },
    { id: 'ps-2', label: 'SNAP Enrollment', completed: true, date: 'Feb 2', metric: 'Active' },
    {
      id: 'ps-3',
      label: 'BH Engagement (12-wk)',
      completed: false,
      date: 'In progress',
      metric: 'Wk 6 of 12',
    },
    { id: 'ps-4', label: 'A1C Recheck', completed: false, date: 'Due Jun 7', metric: 'Last: 9.2' },
    { id: 'ps-5', label: 'A1C Target 7.1', completed: false, metric: 'Goal' },
  ],

  riskLabel: 'Critical — 84% ER risk',
  bhScore: 14,
  bhScoreLabel: 'PHQ-9 14 — Moderate depression',
  aiCopilot:
    'PHQ-9 14 — BH referral open since Mar 15, not yet engaged. COPD exacerbation active — spirometry overdue 42 days. RAF 3.42 with 4 HCC suspects.',

  crisisCount30d: 1,
  lastCrisisDate: '2026-04-15',
  activeCrisis: false,
};
