// ─── sdResourceData.data1.ts ──────────────────────────────────────────────────
// Map center, zip codes, counties, county offices, CBOs, programs,
// crisis resources, and providers.

import type {
  SDCountyOffice,
  SDCBO,
  SDProgram,
  SDCrisisResource,
  SDProvider,
} from './sdResourceData.types';

// ─── SD Map Center (Bennett County, Martin SD) ────────────────────────────────
export const SD_MAP_CENTER = {
  lat: 43.18,
  lng: -101.73,
  label: 'Martin, SD 57551 — Bennett County',
};

// ─── SD Zip Codes ─────────────────────────────────────────────────────────────
export const SD_ZIP_CODES = {
  MARTIN: '57551',
  WINNER: '57580',
  RAPID_CITY: '57701',
  PIERRE: '57501',
  PINE_RIDGE: '57770',
  HOT_SPRINGS: '57747',
  BURKE: '57523',
  GREGORY: '57533',
  SIOUX_FALLS: '57110',
  OGLALA: '57764',
  MOBRIDGE: '57601',
};

// ─── SD Counties ──────────────────────────────────────────────────────────────
export const SD_COUNTIES = [
  'Bennett',
  'Oglala Lakota',
  'Tripp',
  'Fall River',
  'Gregory',
  'Hughes',
  'Pennington',
  'Minnehaha',
  'Shannon',
  'Todd',
];

// ─── SD County Offices ────────────────────────────────────────────────────────
export const SD_COUNTY_OFFICES: SDCountyOffice[] = [
  {
    id: 'co-001',
    name: 'State Benefits Office — Frontier District',
    address: '410 Prairie Ridge Rd',
    city: 'Martin',
    zip: '57551',
    county: 'Bennett',
    phone: '(605) 555-0168',
    fax: '(605) 555-0169',
    hours: 'Mon–Fri 8am–5pm',
    website: 'dss.state.example.org',
    services: ['SNAP', 'TANF', 'Medicaid', 'CCAP', 'Child Support'],
  },
  {
    id: 'co-002',
    name: 'Regional WIC Office',
    address: '410 Prairie Ridge Rd',
    city: 'Martin',
    zip: '57551',
    county: 'Bennett',
    phone: '(605) 555-0168',
    hours: 'Mon–Fri 8am–5pm',
    website: 'doh.state.example.org/wic',
    services: ['WIC — Women, Infants & Children', 'Nutrition counseling', 'Breastfeeding support'],
  },
  {
    id: 'co-003',
    name: 'Highland Community Action Partnership',
    address: '601 Highland St',
    city: 'Rapid City',
    zip: '57701',
    county: 'Pennington',
    phone: '(605) 555-0165',
    hours: 'Mon–Fri 8am–4:30pm',
    website: 'highland-cap.example.org',
    services: ['LIHEAP', 'Emergency assistance', 'Weatherization', 'Head Start'],
  },
  {
    id: 'co-004',
    name: 'State Housing Finance Agency',
    address: '500 Capitol Plaza',
    city: 'Pierre',
    zip: '57501',
    county: 'Hughes',
    phone: '(605) 555-0174',
    hours: 'Mon–Fri 8am–5pm',
    website: 'state-housing.example.org',
    services: ['Rental assistance', 'Section 8 vouchers', 'Homeownership programs'],
  },
  {
    id: 'co-005',
    name: 'State Workforce Office — Frontier District',
    address: '410 Prairie Ridge Rd',
    city: 'Martin',
    zip: '57551',
    county: 'Bennett',
    phone: '(605) 555-0168',
    hours: 'Mon–Fri 8am–5pm',
    website: 'dlr.state.example.org',
    services: ['Job placement', 'WIOA training', 'Unemployment insurance'],
  },
  {
    id: 'co-006',
    name: 'State Benefits Line',
    address: '700 Statehouse Dr',
    city: 'Pierre',
    zip: '57501',
    county: 'Hughes',
    phone: '(605) 555-0173',
    hours: 'Mon–Fri 7am–6pm',
    website: 'dss.state.example.org',
    services: ['SNAP', 'Medicaid', 'TANF', 'CCAP', 'Online applications'],
  },
];

// ─── SD CBOs ──────────────────────────────────────────────────────────────────
export const SD_CBOS: SDCBO[] = [
  {
    id: 'sd-001',
    number: 1,
    name: 'Benefit Enrollment Assistance',
    org: 'Frontier Community Action CBO',
    domain: 'Financial',
    email: 'enroll@frontier-action.example.org',
    phone: '(605) 555-0166',
    address: '212 Frontier Way',
    city: 'Martin',
    county: 'Bennett',
    zip: '57551',
    capacity: 'Accepting',
    connected: true,
    provider: 'uniteus',
    lat: 43.18,
    lng: -101.73,
  },
  {
    id: 'sd-002',
    number: 2,
    name: 'Medical Transportation (NEMT)',
    org: 'Medicaid NEMT — Bennett County',
    domain: 'Transportation',
    email: 'nemt@state.example.org',
    phone: '(800) 555-0190',
    address: '410 Prairie Ridge Rd',
    city: 'Martin',
    county: 'Bennett',
    zip: '57551',
    capacity: 'Accepting',
    connected: true,
    provider: 'uniteus',
    lat: 43.18,
    lng: -101.74,
  },
  {
    id: 'sd-003',
    number: 3,
    name: 'Food Pantry & SNAP Assistance',
    org: 'Prairie Roots Food Network',
    domain: 'Food',
    email: 'food@prairie-roots.example.org',
    phone: '(605) 555-0183',
    address: '45 Cottonwood Dr',
    city: 'Pine Ridge',
    county: 'Oglala Lakota',
    zip: '57770',
    capacity: 'Accepting',
    connected: true,
    provider: 'findhelp',
    lat: 43.02,
    lng: -102.55,
  },
  {
    id: 'sd-004',
    number: 4,
    name: 'Emergency Housing & Shelter',
    org: 'State Housing Finance Agency',
    domain: 'Housing',
    email: 'housing@state-housing.example.org',
    phone: '(605) 555-0174',
    address: '500 Capitol Plaza',
    city: 'Pierre',
    county: 'Hughes',
    zip: '57501',
    capacity: 'Waitlist',
    connected: true,
    provider: 'uniteus',
    lat: 44.37,
    lng: -100.34,
  },
  {
    id: 'sd-005',
    number: 5,
    name: 'Postpartum Support Group',
    org: 'Prairie Health Services',
    domain: 'Mental Health',
    email: 'bh@prairie-health.example.org',
    phone: '(605) 555-0168',
    address: '410 Prairie Ridge Rd',
    city: 'Martin',
    county: 'Bennett',
    zip: '57551',
    capacity: 'Accepting',
    connected: true,
    provider: 'uniteus',
    lat: 43.18,
    lng: -101.73,
  },
  {
    id: 'sd-006',
    number: 6,
    name: 'WIC — Women, Infants & Children',
    org: 'Regional WIC Office',
    domain: 'Nutrition',
    email: 'wic@state-benefits.example.org',
    phone: '(605) 555-0168',
    address: '410 Prairie Ridge Rd',
    city: 'Martin',
    county: 'Bennett',
    zip: '57551',
    capacity: 'Accepting',
    connected: true,
    provider: 'findhelp',
    lat: 43.18,
    lng: -101.73,
  },
  {
    id: 'sd-007',
    number: 7,
    name: 'Childcare Assistance (CCAP)',
    org: 'State Benefits Office — Frontier District',
    domain: 'Childcare',
    email: 'dss@state-benefits.example.org',
    phone: '(605) 555-0168',
    address: '410 Prairie Ridge Rd',
    city: 'Martin',
    county: 'Bennett',
    zip: '57551',
    capacity: 'Accepting',
    connected: true,
    provider: 'uniteus',
    lat: 43.18,
    lng: -101.73,
  },
  {
    id: 'sd-008',
    number: 8,
    name: 'Behavioral Health Services',
    org: 'Cedar Valley BH',
    domain: 'Mental Health',
    email: 'bh@cedar-valley.example.org',
    phone: '(605) 555-0181',
    address: '820 Cedar Bluff Dr',
    city: 'Winner',
    county: 'Tripp',
    zip: '57580',
    capacity: 'Accepting',
    connected: false,
    provider: 'findhelp',
    lat: 43.37,
    lng: -99.86,
  },
  {
    id: 'sd-009',
    number: 9,
    name: 'Employment & Job Training',
    org: 'State Workforce Office — Frontier District',
    domain: 'Employment',
    email: 'jobs@state.example.org',
    phone: '(605) 555-0168',
    address: '410 Prairie Ridge Rd',
    city: 'Martin',
    county: 'Bennett',
    zip: '57551',
    capacity: 'Accepting',
    connected: false,
    provider: 'findhelp',
    lat: 43.18,
    lng: -101.73,
  },
  {
    id: 'sd-010',
    number: 10,
    name: 'Utility Assistance (LIHEAP)',
    org: 'Highland Community Action Partnership',
    domain: 'Utility',
    email: 'liheap@highland-cap.example.org',
    phone: '(605) 555-0165',
    address: '601 Highland St',
    city: 'Rapid City',
    county: 'Pennington',
    zip: '57701',
    capacity: 'Accepting',
    connected: true,
    provider: 'uniteus',
    lat: 44.08,
    lng: -103.23,
  },
  {
    id: 'sd-011',
    number: 11,
    name: 'Tribal Health Services',
    org: 'Tribal Health Program Administration',
    domain: 'Health',
    email: 'health@tribal-health-admin.example.org',
    phone: '(605) 555-0182',
    address: '45 Cottonwood Dr',
    city: 'Pine Ridge',
    county: 'Oglala Lakota',
    zip: '57770',
    capacity: 'Accepting',
    connected: true,
    provider: 'uniteus',
    lat: 43.02,
    lng: -102.55,
  },
  {
    id: 'sd-012',
    number: 12,
    name: 'Crisis & Safety Services',
    org: 'Summit Regional Crisis Line',
    domain: 'Safety',
    email: 'crisis@summit-regional.example.org',
    phone: '(605) 555-0172',
    address: '1450 Summit Ridge Rd',
    city: 'Rapid City',
    county: 'Pennington',
    zip: '57701',
    capacity: 'Accepting',
    connected: true,
    provider: 'uniteus',
    lat: 44.08,
    lng: -103.23,
  },
  {
    id: 'sd-013',
    number: 13,
    name: 'Substance Use Treatment',
    org: 'Riverbend Health Services',
    domain: 'Substance Use',
    email: 'su@riverbend-health.example.org',
    phone: '(605) 555-0171',
    address: '1201 Riverbend Hwy',
    city: 'Hot Springs',
    county: 'Fall River',
    zip: '57747',
    capacity: 'Accepting',
    connected: false,
    provider: 'findhelp',
    lat: 43.43,
    lng: -103.47,
  },
  {
    id: 'sd-014',
    number: 14,
    name: 'Disability & Independent Living',
    org: 'Statewide Disability Advocacy Services',
    domain: 'Disabilities',
    email: 'advocacy@statewide-advocacy.example.org',
    phone: '(605) 555-0159',
    address: '221 S Regional Ave',
    city: 'Pierre',
    county: 'Hughes',
    zip: '57501',
    capacity: 'Accepting',
    connected: false,
    provider: 'findhelp',
    lat: 44.37,
    lng: -100.34,
  },
  {
    id: 'sd-015',
    number: 15,
    name: 'Domestic Violence Services',
    org: 'Safe Harbor Center — Domestic Violence',
    domain: 'Safety',
    email: 'dv@safe-harbor.example.org',
    phone: '(605) 555-0180',
    address: '820 Cedar Bluff Dr',
    city: 'Winner',
    county: 'Tripp',
    zip: '57580',
    capacity: 'Accepting',
    connected: true,
    provider: 'findhelp',
    lat: 43.37,
    lng: -99.86,
  },
  {
    id: 'sd-016',
    number: 16,
    name: 'Education & Literacy',
    org: 'Statewide Literacy Council',
    domain: 'Education',
    email: 'learn@statewide-literacy.example.org',
    phone: '(605) 555-0160',
    address: '104 N Statewide Ave',
    city: 'Pierre',
    county: 'Hughes',
    zip: '57501',
    capacity: 'Accepting',
    connected: false,
    provider: 'findhelp',
    lat: 44.37,
    lng: -100.34,
  },
  {
    id: 'sd-017',
    number: 17,
    name: 'Physical Activity & Wellness',
    org: 'Riverside Medical Associates',
    domain: 'Physical Activity',
    email: 'wellness@riverside-medical.example.org',
    phone: '(605) 555-0179',
    address: '400 Park St',
    city: 'Burke',
    county: 'Gregory',
    zip: '57523',
    capacity: 'Accepting',
    connected: false,
    provider: 'findhelp',
    lat: 43.18,
    lng: -99.29,
  },
  {
    id: 'sd-018',
    number: 18,
    name: 'Financial Counseling',
    org: 'Statewide Credit Counseling Service',
    domain: 'Financial',
    email: 'counsel@statewide-credit.example.org',
    phone: '(605) 555-0162',
    address: '4901 E Metro St',
    city: 'Sioux Falls',
    county: 'Minnehaha',
    zip: '57110',
    capacity: 'Accepting',
    connected: true,
    provider: 'uniteus',
    lat: 43.54,
    lng: -96.73,
  },
];

// ─── SD Programs ──────────────────────────────────────────────────────────────
export const SD_PROGRAMS: SDProgram[] = [
  {
    id: 'prog-wic',
    name: 'WIC — Women, Infants & Children',
    domain: 'Nutrition',
    fundingSource: 'USDA',
    monthlyValue: '$320/mo',
    office: SD_COUNTY_OFFICES[1], // Bennett County WIC
    eligibility: 'Income ≤ 185% FPL · Pregnant, postpartum, or infant/child under 5',
    documents: [
      'Proof of identity (SD ID or tribal ID)',
      'Proof of residency (utility bill or lease)',
      'Proof of income (pay stubs or benefit letter)',
      'Infant/child birth certificate or pregnancy documentation',
    ],
    onlineUrl: 'doh.state.example.org/wic',
  },
  {
    id: 'prog-ccap',
    name: 'SD Childcare Assistance Program (CCAP)',
    domain: 'Childcare',
    fundingSource: 'State Benefits Line',
    monthlyValue: '$487/mo',
    office: SD_COUNTY_OFFICES[0], // State Benefits Office — Frontier District
    eligibility: 'Income ≤ 85% SMI · Working or in school · Child under 13',
    documents: [
      'Proof of identity (SD ID or tribal ID)',
      'Proof of residency in Bennett County',
      'Proof of income (last 30 days)',
      "Child's birth certificate",
      'Childcare provider information',
    ],
    onlineUrl: 'dss.state.example.org/childcare',
  },
  {
    id: 'prog-snap',
    name: 'SNAP Food Assistance',
    domain: 'Food Security',
    fundingSource: 'USDA',
    monthlyValue: '$281/mo',
    office: SD_COUNTY_OFFICES[0], // State Benefits Office — Frontier District
    eligibility: 'Income ≤ 130% FPL · SD resident · Household size verified',
    documents: [
      'Proof of identity',
      'Proof of SD residency',
      'Proof of income or zero-income statement',
      'Social Security numbers for all household members',
    ],
    onlineUrl: 'dss.state.example.org/snap',
  },
  {
    id: 'prog-tanf',
    name: 'TANF — Temporary Assistance for Needy Families',
    domain: 'Financial',
    fundingSource: 'State Benefits Line',
    monthlyValue: '$463/mo',
    office: SD_COUNTY_OFFICES[0], // State Benefits Office — Frontier District
    eligibility: 'Income ≤ 185% FPL · Dependent children · SD resident',
    documents: [
      'Proof of identity',
      'Proof of SD residency',
      'Birth certificates for all children',
      'Proof of income',
      'Social Security cards',
    ],
    onlineUrl: 'dss.state.example.org/tanf',
  },
  {
    id: 'prog-liheap',
    name: 'LIHEAP — Low Income Home Energy Assistance',
    domain: 'Utilities',
    fundingSource: 'Federal LIHEAP',
    monthlyValue: '$180/season',
    office: SD_COUNTY_OFFICES[2], // Community Action Partnership
    eligibility: 'Income ≤ 150% FPL · SD resident · Primary heating source',
    documents: [
      'Proof of identity',
      'Proof of residency',
      'Most recent utility bill',
      'Proof of income',
    ],
    onlineUrl: 'highland-cap.example.org/liheap',
  },
  {
    id: 'prog-sdhda',
    name: 'State Housing Finance Agency — Rental Assistance',
    domain: 'Housing',
    fundingSource: 'State Housing Finance Agency',
    monthlyValue: 'Est. $850/mo',
    office: SD_COUNTY_OFFICES[3], // State Housing Finance Agency Pierre
    eligibility: 'Income ≤ 50% AMI · SD resident · Waitlist position',
    documents: ['Proof of identity', 'Proof of SD residency', 'Proof of income', 'Rental history'],
    onlineUrl: 'state-housing.example.org',
  },
  {
    id: 'prog-nemt',
    name: 'Medicaid Non-Emergency Transportation',
    domain: 'Transportation',
    fundingSource: 'SD Medicaid',
    monthlyValue: 'Covered',
    office: SD_COUNTY_OFFICES[0], // State Benefits Office — Frontier District
    eligibility: 'Active SD Medicaid enrollment · Medical appointment required',
    documents: ['Medicaid ID card', 'Appointment confirmation'],
    onlineUrl: 'dss.state.example.org/medicaid/transport',
  },
];

// ─── SD Crisis Resources ──────────────────────────────────────────────────────
export const SD_CRISIS_RESOURCES: SDCrisisResource[] = [
  {
    id: 'cr-001',
    name: '988 Suicide & Crisis Lifeline — SD',
    type: '988',
    phone: '988',
    description:
      'Call or text 988 — 24/7 mental health crisis support. SD-specific counselors available.',
    available: true,
    responseTime: 'Immediate',
  },
  {
    id: 'cr-002',
    name: 'Summit Regional Crisis Stabilization Unit',
    type: 'CSU',
    phone: '(605) 555-0172',
    description: 'Walk-in crisis stabilization — 23-hour observation, no ED required. Rapid City.',
    available: true,
    responseTime: '< 30 min',
    address: '1450 Summit Ridge Rd',
    city: 'Rapid City',
    zip: '57701',
  },
  {
    id: 'cr-003',
    name: 'Cedar Valley Behavioral Health Mobile Crisis',
    type: 'Mobile',
    phone: '(605) 555-0161',
    description: 'Mobile crisis team dispatch — community-based de-escalation across western SD',
    available: true,
    responseTime: '30–60 min',
    address: '3900 S Statewide Ave',
    city: 'Sioux Falls',
    zip: '57105',
  },
  {
    id: 'cr-004',
    name: 'Cedar Valley Hospital ED',
    type: 'ED',
    phone: '(605) 555-0181',
    description: 'Emergency Department — psychiatric evaluation and stabilization. Winner, SD.',
    available: true,
    responseTime: 'Varies',
    address: '820 Cedar Bluff Dr',
    city: 'Winner',
    zip: '57580',
  },
];

// ─── SD Providers ─────────────────────────────────────────────────────────────
export const SD_PROVIDERS: SDProvider[] = [
  {
    id: 'prov-001',
    name: 'Dr. Carlos Mendez-Ruiz',
    specialty: 'Family Medicine',
    facility: 'Prairie Health Services',
    address: '410 Prairie Ridge Rd',
    city: 'Martin',
    zip: '57551',
    county: 'Bennett',
    phone: '(605) 555-0168',
    tier: 'Preferred',
    acceptingNew: true,
    distanceFromMartin: '0 miles',
    lat: 43.18,
    lng: -101.73,
  },
  {
    id: 'prov-002',
    name: 'Dr. Sofia Reinholt',
    specialty: 'Endocrinology',
    facility: 'Cedar Valley Endocrinology — Winner',
    address: '820 Cedar Bluff Dr',
    city: 'Winner',
    zip: '57580',
    county: 'Tripp',
    phone: '(605) 555-0181',
    tier: 'Preferred',
    acceptingNew: true,
    distanceFromMartin: '47 miles',
    lat: 43.37,
    lng: -99.86,
  },
  {
    id: 'prov-003',
    name: 'Dr. Sarah Nakamura',
    specialty: 'Behavioral Health',
    facility: 'Cedar Valley Behavioral Health — Winner',
    address: '820 Cedar Bluff Dr',
    city: 'Winner',
    zip: '57580',
    county: 'Tripp',
    phone: '(605) 555-0181',
    tier: 'Preferred',
    acceptingNew: true,
    distanceFromMartin: '47 miles',
    lat: 43.37,
    lng: -99.86,
  },
  {
    id: 'prov-004',
    name: 'Dr. Priya Venkataraman',
    specialty: 'Nephrology',
    facility: 'Cedar Valley — Nephrology',
    address: '820 Cedar Bluff Dr',
    city: 'Winner',
    zip: '57580',
    county: 'Tripp',
    phone: '(605) 555-0181',
    tier: 'Preferred',
    acceptingNew: true,
    distanceFromMartin: '47 miles',
    lat: 43.37,
    lng: -99.86,
  },
  {
    id: 'prov-005',
    name: 'Dr. Jerome Blackwood',
    specialty: 'Orthopedics',
    facility: 'Riverbend Health Services',
    address: '1201 Riverbend Hwy',
    city: 'Hot Springs',
    zip: '57747',
    county: 'Fall River',
    phone: '(605) 555-0171',
    tier: 'In-Network',
    acceptingNew: true,
    distanceFromMartin: '112 miles',
    lat: 43.43,
    lng: -103.47,
  },
  {
    id: 'prov-006',
    name: 'Dr. Amara Osei',
    specialty: 'Cardiology',
    facility: 'Summit Regional Cardiology',
    address: '1450 Summit Ridge Rd',
    city: 'Rapid City',
    zip: '57701',
    county: 'Pennington',
    phone: '(605) 555-0172',
    tier: 'Preferred',
    acceptingNew: true,
    distanceFromMartin: '147 miles',
    lat: 44.08,
    lng: -103.23,
  },
  {
    id: 'prov-007',
    name: 'Dr. Thomas Kaczmarek',
    specialty: 'Gastroenterology',
    facility: 'Riverside Medical Associates',
    address: '400 Park St',
    city: 'Burke',
    zip: '57523',
    county: 'Gregory',
    phone: '(605) 555-0179',
    tier: 'In-Network',
    acceptingNew: true,
    distanceFromMartin: '78 miles',
    lat: 43.18,
    lng: -99.29,
  },
  {
    id: 'prov-008',
    name: 'Dr. Nkechi Eze-Williams',
    specialty: 'Family Medicine',
    facility: 'Badlands PCP — Pine Ridge',
    address: '45 Cottonwood Dr',
    city: 'Pine Ridge',
    zip: '57770',
    county: 'Oglala Lakota',
    phone: '(605) 555-0182',
    tier: 'Preferred',
    acceptingNew: true,
    distanceFromMartin: '38 miles',
    lat: 43.02,
    lng: -102.55,
  },
];
