// ─── socialMockData.data1.ts ──────────────────────────────────────────────────
// Patients, PRAPARE domains, screening history, findhelp results,
// program eligibility, and benefit enrollments.

import type {
  SocialPatient,
  ScreeningRecord,
  FindhelpScreeningResult,
  Program,
  Enrollment,
} from './socialMockData.types';
import findhelpSeed from './socialMockData/data/findhelp-results.json';
import programsSeed from './socialMockData/data/programs-by-patient.json';

// ─── Canonical Patients ───────────────────────────────────────────────────────

export const SOCIAL_PATIENTS: SocialPatient[] = [
  {
    id: 'MARIA_SD_001',
    patientId: 'MARIA_SD_001',
    name: 'Maria Redhawk',
    dob: '1992-03-22',
    mrn: 'MRN-SD-001',
    pcp: 'Prairie Health PCP',
    age: 34,
    gender: 'F',
    riskLevel: 'Medium',
    unmetNeeds: 5,
    needs: ['childcare', 'food', 'financial', 'transport', 'housing'],
    lastScreened: '2026-04-15',
    address: '412 Prairie Main St, Martin, SD 57551',
    phone: '(605) 555-0122',
  },
  {
    id: 'PAT-0042',
    patientId: 'PAT-0042',
    name: 'Dorothy Simmons',
    dob: '1951-03-14',
    mrn: 'MRN-0042',
    pcp: 'Dr. Whitfield',
    age: 75,
    gender: 'F',
    riskLevel: 'High',
    unmetNeeds: 4,
    needs: ['housing', 'food', 'social_isolation', 'financial'],
    lastScreened: '2026-01-08',
    address: '3301 Regional Ave, Martin, SD 57551',
    phone: '(605) 555-0142',
  },
  {
    id: 'PAT-0087',
    patientId: 'PAT-0087',
    name: 'James Wilson',
    dob: '1948-07-22',
    mrn: 'MRN-0087',
    pcp: 'Dr. Patel',
    age: 77,
    gender: 'M',
    riskLevel: 'High',
    unmetNeeds: 3,
    needs: ['financial', 'transport', 'social_isolation'],
    lastScreened: '2025-11-14',
    address: '1842 Cedar Bluff Street, Winner, SD 57580',
    phone: '(605) 555-0187',
  },
  {
    id: 'PAT-0103',
    patientId: 'PAT-0103',
    name: 'Robert Chen',
    dob: '1955-11-08',
    mrn: 'MRN-0103',
    pcp: 'Dr. Whitfield',
    age: 70,
    gender: 'M',
    riskLevel: 'Medium',
    unmetNeeds: 2,
    needs: ['food', 'employment'],
    lastScreened: '2026-03-15',
    address: '512 Statehouse Ave, Pierre, SD 57501',
    phone: '(605) 555-0113',
  },
  {
    id: 'PAT-0156',
    patientId: 'PAT-0156',
    name: 'Lisa Thompson',
    dob: '1943-05-30',
    mrn: 'MRN-0156',
    pcp: 'Dr. Kim',
    age: 82,
    gender: 'F',
    riskLevel: 'High',
    unmetNeeds: 3,
    needs: ['housing', 'food', 'transport'],
    lastScreened: '2026-02-20',
    address: '789 Riverside Blvd, Gregory, SD 57533',
    phone: '(605) 555-0156',
  },
  {
    id: 'PAT-0201',
    patientId: 'PAT-0201',
    name: 'James Okafor',
    dob: '1960-09-17',
    mrn: 'MRN-0201',
    pcp: 'Dr. Patel',
    age: 65,
    gender: 'M',
    riskLevel: 'High',
    unmetNeeds: 2,
    needs: ['financial', 'housing'],
    lastScreened: null,
    address: '4400 E Hwy 18, Oglala, SD 57764',
    phone: '(605) 555-0201',
  },
];

// ─── PRAPARE / AHC-HRSN Screening Domains ────────────────────────────────────

export const PRAPARE_DOMAINS = [
  {
    id: 'housing',
    label: 'Housing Instability',
    code: '71802-3',
    question: 'What is your housing situation today?',
    options: ['I have housing', 'I do not have housing', 'I am worried about losing housing'],
    riskOption: 2,
  },
  {
    id: 'food',
    label: 'Food Insecurity',
    code: '88122-7',
    question: 'Within the past 12 months, did you worry that food would run out?',
    options: ['Never true', 'Sometimes true', 'Often true'],
    riskOption: 2,
  },
  {
    id: 'transport',
    label: 'Transportation',
    code: '93030-5',
    question: 'In the past 12 months, has lack of transportation kept you from appointments?',
    options: ['No', 'Yes, some', 'Yes, often'],
    riskOption: 1,
  },
  {
    id: 'social_isolation',
    label: 'Social Isolation',
    code: '93029-7',
    question: 'How often do you feel lonely or isolated?',
    options: ['Never', 'Rarely', 'Sometimes', 'Often', 'Always'],
    riskOption: 3,
  },
  {
    id: 'financial',
    label: 'Financial Strain',
    code: '93031-3',
    question: 'How hard is it to pay for basics like food, housing, medical care?',
    options: ['Not hard at all', 'A little hard', 'Somewhat hard', 'Very hard', 'Extremely hard'],
    riskOption: 3,
  },
  {
    id: 'employment',
    label: 'Employment',
    code: '67875-5',
    question: 'What is your current work situation?',
    options: [
      'Full-time',
      'Part-time',
      'Unemployed — looking',
      'Unemployed — not looking',
      'Retired/Disabled',
    ],
    riskOption: 2,
  },
  {
    id: 'education',
    label: 'Education',
    code: '82589-3',
    question: 'What is the highest level of school you have finished?',
    options: [
      'Less than high school',
      'High school diploma/GED',
      'Some college',
      'College degree or more',
    ],
    riskOption: 0,
  },
  {
    id: 'safety',
    label: 'Personal Safety',
    code: '93038-8',
    question: 'Do you feel physically and emotionally safe where you live?',
    options: ['Yes', 'No'],
    riskOption: 1,
  },
];

export const DOMAIN_COLORS: Record<string, string> = {
  housing: '#da1e28',
  food: '#b45309',
  transport: '#0043ce',
  social_isolation: '#6929c4',
  financial: '#da1e28',
  employment: '#007d79',
  education: '#198038',
  safety: '#da1e28',
};

// ─── Screening History ────────────────────────────────────────────────────────

export const SCREENING_HISTORY: ScreeningRecord[] = [
  {
    id: 'sh-000',
    patientId: 'MARIA_SD_001',
    date: '2026-05-01',
    instrument: 'PRAPARE 13-Domain',
    screener: 'Angela Torres (CHW)',
    unmetNeeds: 7,
    tasksCreated: 5,
    status: 'Completed',
  },
  {
    id: 'sh-001',
    patientId: 'PAT-0042',
    date: '2026-01-08',
    instrument: 'findhelp 13-Domain',
    screener: 'Sarah Johnson (CM)',
    unmetNeeds: 4,
    tasksCreated: 4,
    status: 'Completed',
  },
  {
    id: 'sh-002',
    patientId: 'PAT-0087',
    date: '2025-04-10',
    instrument: 'findhelp 13-Domain',
    screener: 'Sarah Johnson (CM)',
    unmetNeeds: 3,
    tasksCreated: 3,
    status: 'Completed',
  },
  {
    id: 'sh-003',
    patientId: 'PAT-0103',
    date: '2026-03-15',
    instrument: 'Unite Us Screening',
    screener: 'Sarah Johnson (CM)',
    unmetNeeds: 2,
    tasksCreated: 2,
    status: 'Completed',
  },
  {
    id: 'sh-004',
    patientId: 'PAT-0156',
    date: '2026-02-20',
    instrument: 'findhelp 13-Domain',
    screener: 'Robert Chen (CHW)',
    unmetNeeds: 3,
    tasksCreated: 3,
    status: 'Completed',
  },
  {
    id: 'sh-005',
    patientId: 'PAT-0201',
    date: '2026-05-12',
    instrument: 'findhelp 13-Domain',
    screener: 'Sarah Johnson (CM)',
    unmetNeeds: 2,
    tasksCreated: 2,
    status: 'Completed',
  },
];

// ─── findhelp Screening Results ───────────────────────────────────────────────

export const FINDHELP_RESULTS: FindhelpScreeningResult[] =
  findhelpSeed.results as unknown as FindhelpScreeningResult[];

// ─── Program Eligibility ──────────────────────────────────────────────────────

export const PROGRAMS_BY_PATIENT: Record<string, Program[]> =
  programsSeed.byPatient as unknown as Record<string, Program[]>;

// ─── Benefit Enrollments ──────────────────────────────────────────────────────

export const ENROLLMENTS: Enrollment[] = [
  {
    id: 'e-001',
    patientId: 'PAT-0042',
    patient: 'Dorothy Simmons',
    mrn: 'MRN-0042',
    program: 'SNAP Food Assistance',
    domain: 'Food Security',
    fundingSource: 'USDA',
    status: 'expired',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    renewalDeadline: '2025-11-30',
    daysToRenewal: -183,
    benefitValue: '$234/mo',
    caseWorker: 'DHS Case Worker',
    coverageGap: 'Expired Dec 31, 2025 — no food assistance for 5 months',
  },
  {
    id: 'e-002',
    patientId: 'PAT-0042',
    patient: 'Dorothy Simmons',
    mrn: 'MRN-0042',
    program: 'Section 8 Voucher',
    domain: 'Housing',
    fundingSource: 'HUD',
    status: 'pending',
    startDate: '—',
    endDate: '—',
    renewalDeadline: '—',
    daysToRenewal: 999,
    benefitValue: 'Est. $850/mo',
    caseWorker: 'Housing Authority',
    coverageGap: 'Application pending since Feb 2026 — no housing subsidy active',
  },
  {
    id: 'e-003',
    patientId: 'PAT-0042',
    patient: 'Dorothy Simmons',
    mrn: 'MRN-0042',
    program: 'CCBHC BH Services',
    domain: 'Behavioral Health',
    fundingSource: 'BH Block Grant',
    status: 'active',
    startDate: '2025-06-01',
    endDate: '2026-12-31',
    renewalDeadline: '2026-11-30',
    daysToRenewal: 181,
    benefitValue: 'Covered',
    caseWorker: 'BH Counselor',
  },
  {
    id: 'e-004',
    patientId: 'PAT-0042',
    patient: 'Dorothy Simmons',
    mrn: 'MRN-0042',
    program: 'Meals on Wheels',
    domain: 'Food Security',
    fundingSource: 'Older Americans Act',
    status: 'pending',
    startDate: '—',
    endDate: '—',
    renewalDeadline: '—',
    daysToRenewal: 999,
    benefitValue: 'Est. 5 meals/wk',
    caseWorker: 'Area Agency on Aging',
    coverageGap: 'Waitlist position 4 — food gap continues',
  },
  {
    id: 'e-005',
    patientId: 'PAT-0042',
    patient: 'Dorothy Simmons',
    mrn: 'MRN-0042',
    program: 'CHW Outreach',
    domain: 'Care Coordination',
    fundingSource: 'Medicaid 1115',
    status: 'active',
    startDate: '2026-01-15',
    endDate: '2026-12-31',
    renewalDeadline: '2026-11-30',
    daysToRenewal: 181,
    benefitValue: 'Included',
    caseWorker: 'Sarah Johnson (CM)',
  },
  {
    id: 'e-006',
    patientId: 'PAT-0087',
    patient: 'James Wilson',
    mrn: 'MRN-0087',
    program: 'Medicaid BH Services',
    domain: 'Behavioral Health',
    fundingSource: 'Medicaid',
    status: 'active',
    startDate: '2025-03-01',
    endDate: '2026-12-31',
    renewalDeadline: '2026-11-30',
    daysToRenewal: 181,
    benefitValue: 'Covered',
    caseWorker: 'BH Counselor',
  },
  {
    id: 'e-007',
    patientId: 'PAT-0087',
    patient: 'James Wilson',
    mrn: 'MRN-0087',
    program: 'Medicaid Transport',
    domain: 'Transportation',
    fundingSource: 'Medicaid',
    status: 'active',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    renewalDeadline: '2026-11-30',
    daysToRenewal: 181,
    benefitValue: 'Covered',
    caseWorker: 'Transport Coordinator',
  },
  {
    id: 'e-008',
    patientId: 'PAT-0087',
    patient: 'James Wilson',
    mrn: 'MRN-0087',
    program: 'SSI Supplemental Income',
    domain: 'Financial',
    fundingSource: 'SSA',
    status: 'active',
    startDate: '2018-01-01',
    endDate: '2026-12-31',
    renewalDeadline: '2026-11-30',
    daysToRenewal: 181,
    benefitValue: '$914/mo',
    caseWorker: 'SSA Case Worker',
  },
  {
    id: 'e-009',
    patientId: 'PAT-0103',
    patient: 'Robert Chen',
    mrn: 'MRN-0103',
    program: 'SNAP Food Assistance',
    domain: 'Food Security',
    fundingSource: 'USDA',
    status: 'active',
    startDate: '2025-09-01',
    endDate: '2026-08-31',
    renewalDeadline: '2026-07-31',
    daysToRenewal: 59,
    benefitValue: '$281/mo',
    caseWorker: 'DHS Case Worker',
  },
  {
    id: 'e-010',
    patientId: 'PAT-0103',
    patient: 'Robert Chen',
    mrn: 'MRN-0103',
    program: 'Workforce Development',
    domain: 'Employment',
    fundingSource: 'WIOA',
    status: 'pending',
    startDate: '—',
    endDate: '—',
    renewalDeadline: '—',
    daysToRenewal: 999,
    benefitValue: 'Job training',
    caseWorker: 'Workforce Dev Center',
    coverageGap: 'Enrollment not yet completed — employment gap continues',
  },
  {
    id: 'e-011',
    patientId: 'PAT-0156',
    patient: 'Lisa Thompson',
    mrn: 'MRN-0156',
    program: 'Emergency Housing',
    domain: 'Housing',
    fundingSource: 'HUD ESG',
    status: 'active',
    startDate: '2026-03-01',
    endDate: '2026-08-31',
    renewalDeadline: '2026-07-31',
    daysToRenewal: 59,
    benefitValue: '$1,200/mo',
    caseWorker: 'Housing CBO',
  },
  {
    id: 'e-012',
    patientId: 'PAT-0156',
    patient: 'Lisa Thompson',
    mrn: 'MRN-0156',
    program: 'SNAP Food Assistance',
    domain: 'Food Security',
    fundingSource: 'USDA',
    status: 'active',
    startDate: '2025-09-01',
    endDate: '2026-08-31',
    renewalDeadline: '2026-07-31',
    daysToRenewal: 59,
    benefitValue: '$281/mo',
    caseWorker: 'DHS Case Worker',
  },
  {
    id: 'e-013',
    patientId: 'PAT-0156',
    patient: 'Lisa Thompson',
    mrn: 'MRN-0156',
    program: 'CHW Outreach',
    domain: 'Care Coordination',
    fundingSource: 'Medicaid 1115',
    status: 'active',
    startDate: '2026-01-15',
    endDate: '2026-12-31',
    renewalDeadline: '2026-11-30',
    daysToRenewal: 181,
    benefitValue: 'Included',
    caseWorker: 'Sarah Johnson (CM)',
  },
  {
    id: 'e-014',
    patientId: 'PAT-0201',
    patient: 'James Okafor',
    mrn: 'MRN-0201',
    program: 'Medicaid BH Services',
    domain: 'Behavioral Health',
    fundingSource: 'Medicaid',
    status: 'active',
    startDate: '2025-10-01',
    endDate: '2026-12-31',
    renewalDeadline: '2026-11-30',
    daysToRenewal: 181,
    benefitValue: 'Covered',
    caseWorker: 'BH Counselor',
  },
  {
    id: 'e-015',
    patientId: 'PAT-0201',
    patient: 'James Okafor',
    mrn: 'MRN-0201',
    program: 'SSI Disability (Pending)',
    domain: 'Financial',
    fundingSource: 'SSA',
    status: 'pending',
    startDate: '—',
    endDate: '—',
    renewalDeadline: '—',
    daysToRenewal: 999,
    benefitValue: 'Est. $914/mo',
    caseWorker: 'SSA Case Worker',
    coverageGap: 'Disability determination pending — no income support active',
  },
];
