// ─── orchestration/payloads.ts ────────────────────────────────────────────────
// Foundational payloads (signal → finops). Merged with INTERVENTION_PAYLOADS
// from payloads.intervention.ts to produce the exported JSON_PAYLOADS map.

/* eslint-disable @typescript-eslint/no-explicit-any */

import { INTERVENTION_PAYLOADS } from './payloads.intervention';

const FOUNDATIONAL_PAYLOADS: Record<string, object> = {
  signal_classification: {
    engineId: 'SIGNAL_CLASSIFICATION_ENGINE',
    action: 'CLASSIFICATION_COMPLETE',
    timestamp: '2024-11-15T14:22:57Z',
    memberId: 'MARIA_SD_001',
    signals: [
      { type: 'AUTH_EXPIRY', severity: 'HIGH', source: 'Claims System', detail: 'CAREGAP_HBA1C expiring T-4 days · HbA1c lab order · Bennett County Health · Cedar Bluff Regional Healthcare' },
      { type: 'CARE_GAP', severity: 'HIGH', source: 'EHR/Quality Engine', detail: 'HbA1c gap open 45 days · last value 9.2% · Q4 SD Medicaid quality window closes Dec 31' },
      { type: 'BEHAVIORAL', severity: 'MEDIUM', source: 'Engagement Platform', detail: 'Portal logins 3x this week · receptivity 87% · caregiver stress elevated' },
    ],
    concurrentWindow: '30s',
    complexityScore: 'HIGH',
    contextFlags: ['CAREGIVER_RELATIONSHIP', 'DEPENDENT_RELATIONSHIP', 'Q4_SD Medicaid quality_WINDOW', 'POSTPARTUM_EPISODE_DAY427'],
    routingTarget: 'SUPER_ORCHESTRATION_CONTROLLER',
  },
  marketplace_query: {
    queryId: 'REGISTRY_QUERY_MARIA_SD_001_001',
    controllerAction: 'AGENT_MARKETPLACE_QUERY',
    timestamp: '2024-11-15T14:23:02Z',
    queryContext: {
      signalTypes: ['AUTH_EXPIRY', 'CARE_GAP', 'BEHAVIORAL'],
      memberContext: 'HIGH_RISK_POSTPARTUM_DAY427',
      relationshipContext: ['CAREGIVER', 'DEPENDENT'],
      operationalContext: ['Q4_SD Medicaid quality_WINDOW', 'TCOC_CEILING', 'AUTH_WINDOW'],
    },
    registryScanned: 31,
    matchedAgents: 8,
    unmatchedAgents: 23,
    coalitionAssembled: true,
    governanceOverlay: 'MANDATORY',
    matchedAgentRoster: [
      { rank: 1, agentId: 'CARE_AGENT_H1AB', agentName: 'Clinical Care Agent · H1AB Authorization', tier: 'FOUNDATION', matchScore: 0.97, confidenceScore: 0.94, matchReasons: ['AUTH_EXPIRY signal active', 'POSTPARTUM_EPISODE_DAY427 context', 'Q4_SD Medicaid quality_WINDOW operational flag'], assignedRole: 'PRIMARY_CARE_COORDINATOR' },
      { rank: 2, agentId: 'UTILIZATION_AGENT', agentName: 'Eligibility Management Agent', tier: 'FOUNDATION', matchScore: 0.95, confidenceScore: 0.91, matchReasons: ['AUTH_WINDOW context match', 'TCOC_CEILING exposure flag', 'Postpartum episode utilization pattern'], assignedRole: 'UTILIZATION_REVIEWER' },
      { rank: 3, agentId: 'FINANCIAL_INTELLIGENCE_AGENT', agentName: 'Financial Intelligence Agent', tier: 'FOUNDATION', matchScore: 0.93, confidenceScore: 0.89, matchReasons: ['TCOC_CEILING operational context', 'Q4_SD Medicaid quality_WINDOW financial exposure', 'HIGH_RISK member tier'], assignedRole: 'FINANCIAL_MODELER' },
      { rank: 4, agentId: 'SIGNAL_DISPOSITION_AGENT', agentName: 'Signal Disposition Agent', tier: 'FOUNDATION', matchScore: 0.91, confidenceScore: 0.88, matchReasons: ['Multi-signal triage required', 'AUTH_EXPIRY + CARE_GAP + BEHAVIORAL co-occurrence', 'Priority scoring active'], assignedRole: 'SIGNAL_TRIAGER' },
      { rank: 5, agentId: 'CAREGIVER_INTELLIGENCE_AGENT', agentName: 'Caregiver Intelligence Agent', tier: 'OPERATIONAL', matchScore: 0.88, confidenceScore: 0.85, matchReasons: ['CAREGIVER relationship context', 'Elena Redhawk proxy thread active', 'DEPENDENT relationship flag'], assignedRole: 'CAREGIVER_COORDINATOR' },
      { rank: 6, agentId: 'PROVIDER_ENABLEMENT_AGENT', agentName: 'Social / SDOH Agent', tier: 'OPERATIONAL', matchScore: 0.84, confidenceScore: 0.82, matchReasons: ['Eligibility gap detected', 'AUTH_EXPIRY requires provider validation', 'Network adequacy check needed'], assignedRole: 'PROVIDER_VALIDATOR' },
      { rank: 7, agentId: 'APPEALS_AGENT', agentName: 'Appeals & Grievance Agent', tier: 'OPERATIONAL', matchScore: 0.81, confidenceScore: 0.79, matchReasons: ['AUTH_EXPIRY creates appeal risk', 'POSTPARTUM_EPISODE_DAY427 clinical urgency', 'Q4_SD Medicaid quality_WINDOW deadline pressure'], assignedRole: 'APPEALS_HANDLER' },
      { rank: 8, agentId: 'Med review_AGENT', agentName: 'Medication Therapy Management Agent', tier: 'OPERATIONAL', matchScore: 0.78, confidenceScore: 0.76, matchReasons: ['BEHAVIORAL signal includes medication adherence', 'Postpartum medication reconciliation required', 'Duplicate therapy risk flag'], assignedRole: 'Med review_REVIEWER' },
    ],
    unmatchedAgentSample: [
      { agentId: 'DENTAL_BENEFITS_AGENT', agentName: 'Dental Benefits Agent', tier: 'OPERATIONAL', matchScore: 0.12, exclusionReason: 'No dental signal present; member context is postpartum/behavioral only' },
      { agentId: 'VISION_CARE_AGENT', agentName: 'Vision Clinical Care Agent', tier: 'OPERATIONAL', matchScore: 0.09, exclusionReason: 'Vision signal absent; no ophthalmology context in episode' },
      { agentId: 'MATERNITY_AGENT', agentName: 'Maternity & NICU Agent', tier: 'OPERATIONAL', matchScore: 0.04, exclusionReason: 'Member demographic mismatch; maternity context not applicable' },
      { agentId: 'BEHAVIORAL_CRISIS_AGENT', agentName: 'Behavioral Crisis Intervention Agent', tier: 'OPERATIONAL', matchScore: 0.31, exclusionReason: 'BEHAVIORAL signal present but below crisis threshold; standard care agent sufficient' },
      { agentId: 'TRANSPLANT_COORDINATION_AGENT', agentName: 'Transplant Coordination Agent', tier: 'SPECIALTY', matchScore: 0.07, exclusionReason: 'No transplant episode or organ waitlist context detected' },
      { agentId: 'PEDIATRIC_CARE_AGENT', agentName: 'Pediatric Clinical Care Agent', tier: 'OPERATIONAL', matchScore: 0.06, exclusionReason: 'Member age 67; adult care pathway applies' },
      { agentId: 'ONCOLOGY_AGENT', agentName: 'Oncology Navigation Agent', tier: 'SPECIALTY', matchScore: 0.14, exclusionReason: 'No active oncology diagnosis in member record; postpartum episode primary' },
      { agentId: 'WORKER_COMP_AGENT', agentName: "Worker's Compensation Agent", tier: 'OPERATIONAL', matchScore: 0.02, exclusionReason: 'No occupational injury claim; commercial health plan context only' },
      { agentId: 'SNOMED_CODING_AGENT', agentName: 'Clinical Coding Accuracy Agent', tier: 'QUALITY', matchScore: 0.22, exclusionReason: 'Coding review not triggered; AUTH_EXPIRY does not require recoding at this stage' },
      { agentId: 'FRAUD_WASTE_ABUSE_AGENT', agentName: 'Fraud, Waste & Abuse Detection Agent', tier: 'GOVERNANCE', matchScore: 0.18, exclusionReason: 'No anomaly pattern detected; claim history within expected variance for postpartum episode' },
    ],
    unmatchedAgentCount: 23,
    unmatchedSampleNote: 'Showing 10 of 23 unmatched agents. Remaining 13 excluded due to specialty mismatch, inactive contract status, or member demographic filters.',
  },
  graph_intel_push: {
    agentId: 'GRAPH_INTELLIGENCE',
    action: 'CONTEXT_ASSEMBLED',
    timestamp: '2024-11-15T14:23:00Z',
    memberId: 'MARIA_SD_001',
    graphNodes: 14,
    graphEdges: 17,
    identityConfidence: 0.97,
    resolvedRelationships: ['PARENT_OF → Sophia', 'CAREGIVER_FOR → Elena'],
    contextPackage: 'ORCHESTRATION_CONTEXT_001',
    auditId: 'AUDIT_20241115_142300_GRAPH_001',
  },
  identity_push: {
    agentId: 'IDENTITY_RESOLUTION',
    action: 'GOLDEN_RECORD_COMMITTED',
    timestamp: '2024-11-15T14:23:08Z',
    memberId: 'MARIA_SD_001',
    sourcesReconciled: 4,
    conflictsResolved: 3,
    goldenRecordId: 'GR_MARIA_SD_001',
    confidence: 0.97,
    authoritativeSource: 'CLAIMS',
    auditId: 'AUDIT_20241115_142308_IDENTITY_001',
  },
  consent_push: {
    agentId: 'CONSENT_AGENT',
    action: 'CONSENT_GATE_OPENED',
    timestamp: '2024-11-15T14:23:15Z',
    memberId: 'MARIA_SD_001',
    consentScope: 'FULL',
    proxyConsentFor: 'Elena Redhawk',
    proxyScope: ['MEDICATION_MGMT', 'APPT_COORDINATION'],
    consentGateStatus: 'OPEN',
    boundaryEnforced: true,
    auditId: 'AUDIT_20241115_142315_CONSENT_001',
  },
  person_state_push: {
    agentId: 'PERSON_STATE_INTELLIGENCE',
    action: 'STATE_PROFILE_ASSEMBLED',
    timestamp: '2024-11-15T14:23:18Z',
    memberId: 'MARIA_SD_001',
    behavioralState: 'ENGAGED',
    portalEngagement: '3 logins this week',
    receptivityScore: 0.87,
    communicationFatigue: 'LOW',
    lifeEventSignals: ['CAREGIVER_STRESS_ELEVATED', 'DEPENDENT_CARE_GAP'],
    recommendedChannel: 'PORTAL',
    recommendedTiming: '10am — peak engagement window',
    auditId: 'AUDIT_20241115_142318_PERSON_001',
  },
  care_push: {
    agentId: 'CARE_MANAGEMENT',
    action: 'AUTH_EVIDENCE_SUBMITTED',
    timestamp: '2024-11-15T14:31:08Z',
    memberId: 'MARIA_SD_001',
    authorizationId: 'CAREGAP_HBA1C',
    procedureCode: 'HbA1c',
    procedureDescription: 'HbA1c lab — transthoracic',
    expiryDaysRemaining: 4,
    clinicalEvidence: {
      diagnosisCodes: ['I25.10', 'E11.9'],
      primaryDiagnosis: 'Chronic ischemic heart disease, unspecified',
      supportingRecords: 3,
      medicalNecessityBasis: 'Active postpartum episode Day 427 — ongoing monitoring required per SD Medicaid LCD L38779',
      priorAuthHistory: 'AUTH_000 approved 2024-08-15 — same procedure, same provider',
    },
    sdohBarrierResolved: {
      barrierType: 'TRANSPORT_PROBABLE',
      resolution: 'Home lab kit dispatched 2024-11-14 — eliminates clinic transport requirement',
      evidence: '2 missed appointments in 12 months — same zip code pattern',
    },
    governanceCheck: 'PASSED',
    auditId: 'AUDIT_20241115_143108_CARE_001',
  },
  provider_push: {
    agentId: 'PROVIDER_ENABLEMENT',
    action: 'CREDENTIALING_RENEWAL_INITIATED',
    timestamp: '2024-11-15T14:45:22Z',
    providerId: 'NPI_1234567890',
    providerName: 'Bennett County Health',
    specialty: 'Cardiology',
    facility: 'Bennett County Health',
    eligibilityStatus: 'EXPIRING',
    renewalDeadlineDays: 21,
    renewalDeadlineDate: '2024-12-06',
    activeEpisodesAtRisk: 12,
    episodesProtectedByRenewal: 12,
    renewalWorkflow: 'AUTOMATED — no human intervention required',
    eligibilitySystemRef: 'CRED_RENEWAL_20241115_001',
    networkAdequacyImpact: 'NONE — renewal initiated before lapse',
    auditId: 'AUDIT_20241115_144522_PROV_001',
  },
  utilization_push: {
    agentId: 'UTILIZATION_MANAGEMENT',
    action: 'AUTH_RECORD_UPDATED',
    timestamp: '2024-11-15T14:31:08Z',
    authorizationId: 'CAREGAP_HBA1C',
    procedureCode: 'HbA1c',
    clinicalGuidelineRef: 'SD Medicaid_LCD_L38779',
    medicalNecessityVerdict: 'APPROVED — criteria met',
    criteriaApplied: [
      'Active postpartum episode with documented prior auth history',
      'Diagnosis I25.10 meets echocardiography indication threshold',
      'Day 34 of 90-day episode — monitoring interval appropriate',
    ],
    payerSystemUpdate: 'SUBMITTED',
    authCycleTimeDays: 0.3,
    previousCycleTimeDays: 8.2,
    improvementPct: 96,
    mlrExposureReduced: true,
    auditId: 'AUDIT_20241115_143108_UTIL_001',
  },
  appeals_push: {
    agentId: 'APPEALS_GRIEVANCES',
    action: 'HOLD_FOR_HUMAN_REVIEW',
    timestamp: '2024-11-15T14:31:22Z',
    appealId: 'APPEAL_20241115_001',
    appealType: 'CLINICAL_NECESSITY_DETERMINATION',
    interceptedBy: 'POLICY_BOUNDARY',
    policyTriggered: 'SD Medicaid.APPEAL.AUTO.THRESHOLD.001',
    reason: 'Clinical necessity determination for postpartum care procedure exceeds automated authority — physician review required',
    automatedActionAttempted: 'DISPATCH_APPEAL_WITHOUT_PHYSICIAN_SIGN_OFF',
    disposition: 'HOLD_FOR_HUMAN_REVIEW',
    reviewerNotified: 'Dr. K. Patel — Medical Director',
    reviewerNotifiedAt: '2024-11-15T14:31:25Z',
    deadlineHoursRemaining: 68,
    regulatoryDeadline: 'SD Medicaid 72-hour prior auth review standard',
    contextPackageAssembled: true,
    contextPackageRef: 'APPEAL_CTX_20241115_001',
    auditId: 'AUDIT_20241115_143122_APPEALS_001',
  },
  financial_push: {
    agentId: 'FINANCIAL_INTELLIGENCE',
    action: 'MEMBER_PORTAL_UPDATED',
    timestamp: '2024-11-15T14:38:00Z',
    memberId: 'MARIA_SD_001',
    calculationBasis: {
      planYear: 2024,
      deductibleMet: 1200,
      deductibleRemaining: 300,
      oopMaxRemaining: 1840,
      procedureCode: 'HbA1c',
      networkStatus: 'IN_NETWORK — Cedar Bluff Regional Healthcare',
    },
    oopLiabilityRange: { min: 340, max: 480, currency: 'USD', confidence: 'HIGH' },
    outOfNetworkExposureAvoided: 2400,
    referralInitiated: 'Dr. Sarah Kim — in-network cardiologist',
    costSummarySent: true,
    costSummaryChannel: 'MEMBER_PORTAL — widget pushed',
    benefitsEngineRef: 'BENEFITS_CALC_20241115_001',
    financialSurpriseRisk: 'ELIMINATED',
    auditId: 'AUDIT_20241115_143800_FIN_001',
  },
  caregiver_push: {
    agentId: 'CAREGIVER_INTELLIGENCE',
    action: 'BLOCKED_BY_GOVERNANCE',
    timestamp: '2024-11-15T14:42:19Z',
    attemptedAction: 'SHARE_MEDICATION_LIST_THIRD_PARTY',
    blockedBy: 'POLICY_BOUNDARY',
    policyTriggered: 'CONSENT.PROXY.SCOPE.BOUNDARY.001',
    proxyGrantor: 'Elena Redhawk',
    proxyConsentScope: ['MEDICATION_MGMT', 'APPT_COORDINATION'],
    scopeExceeded: 'THIRD_PARTY_DISCLOSURE — medication list to external care coordinator',
    actionWithinScope: {
      inrMonitoringInitiated: true,
      lisinoprilInteractionFlagged: true,
      elenaThreadUpdated: true,
      note: "A1C monitoring and Lisinopril flag actioned within Elena's granted proxy scope",
    },
    resolution: 'Elena must grant expanded scope OR care coordinator contacts Maria directly under separate NPP',
    auditId: 'AUDIT_20241115_144219_CARE_001',
  },
  finops_push: {
    agentId: 'FINOPS_AGENT',
    action: 'COST_CAPTURE_COMPLETE',
    timestamp: '2024-11-15T14:48:00Z',
    scenarioId: 'SCENARIO_MARIA_SD_001',
    interventionCosts: {
      estimated: 2840,
      actual: 2650,
      variance: -190,
      variancePct: -6.7,
      underBudgetReason: 'Automated auth renewal eliminated 2 manual review cycles',
    },
    costAvoidance: {
      total: 18400,
      breakdown: {
        avoidedReadmission: 14200,
        manualProcessingEliminated: 2800,
        duplicateTherapyResolved: 1400,
      },
    },
    tcocImpact: -0.003,
    interventionType: 'AUTH_RENEWAL + CARE_GAP_CLOSURE + DUPLICATE_THERAPY_RESOLUTION',
    auditId: 'AUDIT_20241115_144800_FINOPS_001',
  },
};

export const JSON_PAYLOADS: Record<string, object> = {
  ...FOUNDATIONAL_PAYLOADS,
  ...INTERVENTION_PAYLOADS,
};
