/**
 * RTF lookup tables (data) — the destination-keyword set, literal-character map, and Windows-1252
 * high-range decode. Split out of `docIntake.ts` so the RTF logic and the intake orchestrator each
 * stay under the size cap. Data only; no logic beyond the cp1252 decode helper.
 */

// Control words whose GROUP contents are not body text (font/color/style tables, metadata,
// embedded objects/pictures, field instructions, list-table definitions, etc.). Marking the word
// ignorable suppresses output until the enclosing group closes. NOTE: the list MARKER groups
// (\listtext, \pntext…) are intentionally NOT here — their text is the visible marker (handled by
// LITERAL_MARKER in docIntakeRtf) — but the list DEFINITION tables (\listtable, \listoverridetable)
// are, so they don't leak into body text; they're parsed separately from the raw RTF.
export const RTF_DESTINATIONS = new Set<string>([
  'aftncn',
  'aftnsep',
  'aftnsepc',
  'annotation',
  'atnauthor',
  'atndate',
  'atnicn',
  'atnid',
  'atnparent',
  'atnref',
  'atntime',
  'atrfend',
  'atrfstart',
  'author',
  'background',
  'bkmkend',
  'bkmkstart',
  'blipuid',
  'buptim',
  'category',
  'colorschememapping',
  'colortbl',
  'comment',
  'company',
  'creatim',
  'datafield',
  'datastore',
  'defchp',
  'defpap',
  'do',
  'doccomm',
  'docvar',
  'dptxbxtext',
  'ebcend',
  'ebcstart',
  'factoidname',
  'falt',
  'fchars',
  'ffdeftext',
  'ffentrymcr',
  'ffexitmcr',
  'ffformat',
  'ffhelptext',
  'ffl',
  'ffname',
  'ffstattext',
  'field',
  'file',
  'filetbl',
  'fldinst',
  'fldtype',
  'fname',
  'fontemb',
  'fontfile',
  'fonttbl',
  'footerf',
  'footerl',
  'footerr',
  'footnote',
  'formfield',
  'ftncn',
  'ftnsep',
  'ftnsepc',
  'g',
  'generator',
  'gridtbl',
  'headerf',
  'headerl',
  'headerr',
  'hl',
  'hlfr',
  'hlinkbase',
  'hlloc',
  'hlsrc',
  'hsv',
  'htmltag',
  'info',
  'keycode',
  'keywords',
  'latentstyles',
  'lchars',
  'levelnumbers',
  'leveltext',
  'lfolevel',
  'linkval',
  'list',
  'listlevel',
  'listname',
  'listoverride',
  'listoverridetable',
  'listpicture',
  'liststylename',
  'listtable',
  'lsdlockedexcept',
  'macc',
  'maccPr',
  'mailmerge',
  'maln',
  'malnScr',
  'manager',
  'margPr',
  'mbar',
  'mbarPr',
  'mbaseJc',
  'mbegChr',
  'mborderBox',
  'mborderBoxPr',
  'mbox',
  'mchr',
  'mcount',
  'mctrlPr',
  'md',
  'mdeg',
  'mdegHide',
  'mden',
  'mdiff',
  'mdPr',
  'me',
  'mendChr',
  'meqArr',
  'meqArrPr',
  'mf',
  'mfName',
  'mfPr',
  'mfunc',
  'mfuncPr',
  'mgroupChr',
  'mgroupChrPr',
  'mgrow',
  'mhideBot',
  'mhideLeft',
  'mhideRight',
  'mhideTop',
  'mhtmltag',
  'mlim',
  'mlimloc',
  'mlimlow',
  'mlimlowPr',
  'mlimupp',
  'mlimuppPr',
  'mm',
  'mmaddfieldname',
  'mmath',
  'mmathPict',
  'mmathPr',
  'mmaxdist',
  'mmc',
  'mmcJc',
  'mmconnectstr',
  'mmconnectstrdata',
  'mmcPr',
  'mmcs',
  'mmdatasource',
  'mmheadersource',
  'mmmailsubject',
  'mmodso',
  'mmodsofilter',
  'mmodsofldmpdata',
  'mmodsomappedname',
  'mmodsoname',
  'mmodsorecipdata',
  'mmodsosort',
  'mmodsosrc',
  'mmodsotable',
  'mmodsoudl',
  'mmodsoudldata',
  'mmodsouniquetag',
  'mmPr',
  'mmquery',
  'mmr',
  'mnary',
  'mnaryPr',
  'mnoBreak',
  'mnum',
  'mobjDist',
  'moMath',
  'moMathPara',
  'moMathParaPr',
  'mopEmu',
  'mphant',
  'mphantPr',
  'mplcHide',
  'mpol',
  'mqSubPr',
  'mr',
  'mrad',
  'mradPr',
  'mrPr',
  'msepChr',
  'mshow',
  'mshp',
  'msPre',
  'msPrePr',
  'msSub',
  'msSubPr',
  'msSubSup',
  'msSubSupPr',
  'msSup',
  'msSupPr',
  'mstrikeBLTR',
  'mstrikeH',
  'mstrikeTLBR',
  'mstrikeV',
  'msub',
  'msubHide',
  'msup',
  'msupHide',
  'mtransp',
  'mtype',
  'mvertJc',
  'mvfmf',
  'mvfml',
  'mvtof',
  'mvtol',
  'mzeroAsc',
  'mzeroDesc',
  'mzeroWid',
  'nesttableprops',
  'nextfile',
  'nonesttables',
  'objalias',
  'objclass',
  'objdata',
  'object',
  'objname',
  'objsect',
  'objtime',
  'oldcprops',
  'oldpprops',
  'oldsprops',
  'oldtprops',
  'oleclsid',
  'operator',
  'panose',
  'password',
  'passwordhash',
  'pgp',
  'pgptbl',
  'picprop',
  'pict',
  'pn',
  'pnseclvl',
  'printim',
  'private',
  'propname',
  'protend',
  'protstart',
  'protusertbl',
  'pxe',
  'result',
  'revtbl',
  'revtim',
  'rsidtbl',
  'rxe',
  'shp',
  'shpgrp',
  'shpinst',
  'shppict',
  'shprslt',
  'shptxt',
  'sn',
  'sp',
  'staticval',
  'stylesheet',
  'subject',
  'sv',
  'svb',
  'tc',
  'template',
  'themedata',
  'title',
  'txe',
  'ud',
  'upr',
  'userprops',
  'wgrffmtfilter',
  'windowcaption',
  'writereservation',
  'writereservhash',
  'xe',
  'xform',
  'xmlattrname',
  'xmlattrvalue',
  'xmlclose',
  'xmlname',
  'xmlnstbl',
  'xmlopen',
]);

// Control words that emit a literal character (line/tab breaks, dashes, smart quotes). Paragraph
// breaks are handled separately (PARA_BREAK) so a reconstructed list marker can be applied.
export const RTF_SPECIAL: Record<string, string> = {
  line: '\n',
  tab: '\t',
  cell: '\t',
  emdash: '—',
  endash: '–',
  emspace: ' ',
  enspace: ' ',
  qmspace: ' ',
  bullet: '•',
  lquote: '‘',
  rquote: '’',
  ldblquote: '“',
  rdblquote: '”',
  ltrmark: '',
  rtlmark: '',
  zwnj: '',
  zwj: '',
};

// Windows-1252 mappings for the 0x80–0x9F range where cp1252 ≠ latin1 (smart punctuation etc.), so
// `\'xx` escapes in that range decode correctly. Bytes outside this range use their code point.
const CP1252_HIGH: Record<number, number> = {
  0x80: 0x20ac,
  0x82: 0x201a,
  0x83: 0x0192,
  0x84: 0x201e,
  0x85: 0x2026,
  0x86: 0x2020,
  0x87: 0x2021,
  0x88: 0x02c6,
  0x89: 0x2030,
  0x8a: 0x0160,
  0x8b: 0x2039,
  0x8c: 0x0152,
  0x8e: 0x017d,
  0x91: 0x2018,
  0x92: 0x2019,
  0x93: 0x201c,
  0x94: 0x201d,
  0x95: 0x2022,
  0x96: 0x2013,
  0x97: 0x2014,
  0x98: 0x02dc,
  0x99: 0x2122,
  0x9a: 0x0161,
  0x9b: 0x203a,
  0x9c: 0x0153,
  0x9e: 0x017e,
  0x9f: 0x0178,
};

export function cp1252Char(byte: number): string {
  if (byte >= 0x80 && byte <= 0x9f) return String.fromCharCode(CP1252_HIGH[byte] ?? byte);
  return String.fromCharCode(byte);
}
