// wpcGraph/mariaJourneyData.ts — authored demo constants for Maria Redhawk's journey screen.
// These are the golden data driving the Journey-Aware Context demo for MARIA_SD_001.
// Preserved verbatim from the original page; do not modify without updating tests.

import type {
  JourneyInteraction,
  SuppressionRule,
  Channel,
  ConversionEntry,
} from './journeyContext';

export const MARIA_INTERACTIONS: JourneyInteraction[] = [
  {
    id: 'sms-1',
    channel: 'sms',
    dayOffset: 2,
    hourOfDay: 15,
    type: 'outreach',
    outcome: 'engaged',
    agent: 'Agent 8',
    note: 'WIC eligibility notice',
    timestamp: 'Day 2 · 3:47 PM',
  },
  {
    id: 'sms-2',
    channel: 'sms',
    dayOffset: 4,
    hourOfDay: 16,
    type: 'response',
    outcome: 'converted',
    agent: 'Agent 10',
    note: 'Childcare subsidy — replied YES',
    timestamp: 'Day 4 · 4:12 PM',
  },
  {
    id: 'sms-3',
    channel: 'sms',
    dayOffset: 7,
    hourOfDay: 15,
    type: 'outreach',
    outcome: 'engaged',
    agent: 'Agent 10',
    note: 'SNAP renewal T+47d reminder',
    timestamp: 'Day 7 · 3:55 PM',
  },
  {
    id: 'sms-4',
    channel: 'sms',
    dayOffset: 14,
    hourOfDay: 16,
    type: 'outreach',
    outcome: 'ignored',
    agent: 'Agent 9',
    note: 'Edinburgh PND screening link',
    timestamp: 'Day 14 · 4:30 PM',
  },
  {
    id: 'sms-5',
    channel: 'sms',
    dayOffset: 21,
    hourOfDay: 17,
    type: 'escalation',
    outcome: 'engaged',
    agent: 'Agent 6',
    note: 'HbA1c appointment coordination',
    timestamp: 'Day 21 · 5:15 PM',
  },
  {
    id: 'sms-6',
    channel: 'sms',
    dayOffset: 28,
    hourOfDay: 8,
    type: 'outreach',
    outcome: 'suppressed',
    agent: 'Consent Agent',
    note: 'Sent outside window — blocked (8 AM)',
    timestamp: 'Day 28 · 8:00 AM',
  },
  {
    id: 'sms-7',
    channel: 'sms',
    dayOffset: 42,
    hourOfDay: 16,
    type: 'response',
    outcome: 'converted',
    agent: 'Agent 10',
    note: 'Transportation CBO — confirmed',
    timestamp: 'Day 42 · 4:05 PM',
  },
  {
    id: 'sms-8',
    channel: 'sms',
    dayOffset: 56,
    hourOfDay: 15,
    type: 'outreach',
    outcome: 'engaged',
    agent: 'Agent 9',
    note: 'Sophia well-child reminder',
    timestamp: 'Day 56 · 3:30 PM',
  },
  {
    id: 'ph-1',
    channel: 'phone',
    dayOffset: 5,
    hourOfDay: 16,
    type: 'inbound',
    outcome: 'engaged',
    agent: 'Sarah Johnson',
    note: 'Called re: childcare subsidy details',
    timestamp: 'Day 5 · 4:45 PM',
  },
  {
    id: 'ph-2',
    channel: 'phone',
    dayOffset: 17,
    hourOfDay: 17,
    type: 'outbound',
    outcome: 'no_answer',
    agent: 'Sarah Johnson',
    note: 'Care manager follow-up attempt',
    timestamp: 'Day 17 · 5:10 PM',
  },
  {
    id: 'ph-3',
    channel: 'phone',
    dayOffset: 34,
    hourOfDay: 16,
    type: 'inbound',
    outcome: 'engaged',
    agent: 'Bennett DSS',
    note: 'Bennett County DSS — benefit question',
    timestamp: 'Day 34 · 4:20 PM',
  },
  {
    id: 'ip-1',
    channel: 'inperson',
    dayOffset: 8,
    hourOfDay: 10,
    type: 'visit',
    outcome: 'converted',
    agent: 'CHW Team',
    note: 'CHW home visit · PRAPARE completed',
    timestamp: 'Day 8 · 10:00 AM',
  },
  {
    id: 'ip-2',
    channel: 'inperson',
    dayOffset: 21,
    hourOfDay: 14,
    type: 'visit',
    outcome: 'engaged',
    agent: 'Sarah Johnson',
    note: 'Bennett County Health PCP',
    timestamp: 'Day 21 · 2:30 PM',
  },
  {
    id: 'po-1',
    channel: 'portal',
    dayOffset: 90,
    hourOfDay: 9,
    type: 'outreach',
    outcome: 'ignored',
    agent: 'System',
    note: 'Portal registration link sent — not opened',
    timestamp: 'Day 90 · 9:00 AM',
  },
  {
    id: 'em-1',
    channel: 'email',
    dayOffset: 60,
    hourOfDay: 9,
    type: 'outreach',
    outcome: 'ignored',
    agent: 'SD DHSS',
    note: 'SD DHSS enrollment notice — no email engagement',
    timestamp: 'Day 60 · 9:00 AM',
  },
];

export const MARIA_SUPPRESSION_RULES: SuppressionRule[] = [
  {
    id: 'sr-1',
    icon: '🚫',
    label: 'No outreach 6:00 AM – 3:00 PM (work hours)',
    color: '#EF4444',
    bg: '#EF444422',
  },
  {
    id: 'sr-2',
    icon: '🚫',
    label: 'No outreach after 7:00 PM (caregiving hours)',
    color: '#EF4444',
    bg: '#EF444422',
  },
  {
    id: 'sr-3',
    icon: '🚫',
    label: 'No portal / email outreach (digital divide)',
    color: '#F59E0B',
    bg: '#F59E0B22',
  },
  {
    id: 'sr-4',
    icon: '🚫',
    label: 'No duplicate SMS within 4 hours',
    color: '#F59E0B',
    bg: '#F59E0B22',
  },
  {
    id: 'sr-5',
    icon: '✓',
    label: 'Caregiver (Elena): SMS only · clinical summary scope · no BH',
    color: '#84CC16',
    bg: '#84CC1622',
  },
  {
    id: 'sr-6',
    icon: '⚠',
    label: 'BH outreach: 42 CFR Part 2 consent required before any BH content',
    color: '#a78bfa',
    bg: '#a78bfa22',
  },
];

export const MARIA_CHANNELS: Channel[] = [
  { key: 'sms', label: 'SMS', color: '#84CC16', inactive: false, note: null },
  { key: 'phone', label: 'Phone', color: '#0EA5E9', inactive: false, note: null },
  { key: 'inperson', label: 'In-Person', color: '#8B5CF6', inactive: false, note: null },
  {
    key: 'portal',
    label: 'Portal',
    color: '#475569',
    inactive: true,
    note: 'No broadband · portal access blocked',
  },
  {
    key: 'mobile',
    label: 'Mobile App',
    color: '#334155',
    inactive: true,
    note: 'App not installed · basic smartphone',
  },
  {
    key: 'email',
    label: 'Email',
    color: '#374151',
    inactive: true,
    note: 'Email not primary — SMS preferred',
  },
];

export const MARIA_CONVERSION_DATA: ConversionEntry[] = [
  { label: 'SMS In-Window', rate: 78, color: '#84CC16', note: 'suppression working' },
  { label: 'SMS Out-Window', rate: 8, color: '#EF4444', note: 'suppression working' },
  { label: 'In-Person CHW', rate: 100, color: '#8B5CF6', note: 'highest value' },
  { label: 'Phone Inbound', rate: 67, color: '#0EA5E9', note: '' },
  { label: 'Portal', rate: 0, color: '#475569', note: 'access barrier' },
];
