// ─── Referral demo data (relocated from ActiveReferralsTable per size doctrine) ──
// Authored mock referrals for the demo cohort — values unchanged; a location
// move only, so the table component stays under the 400-line cap once formatted
// and referral demo data lives in the referrals domain lib.

import type { ReferralRecord } from '@/app/referral-tracking/page';

export const mockReferrals: ReferralRecord[] = [
  {
    id: 'ref-001',
    patientName: 'Maria Redhawk',
    patientId: 'patient-maria',
    referralDate: '2026-05-10',
    specialty: 'Endocrinology',
    urgency: 'Urgent',
    status: 'In Progress',
    assignedProvider: 'Dr. Sofia Reinholt — Cedar Valley Endocrinology',
    providerId: 'prov-002',
    providerTier: 'Preferred',
    icdCode: 'R73.09',
    icdDescription: 'Pre-diabetes (A1C 6.2%)',
    submissionChannel: 'Epic Direct',
    submittedDate: '2026-05-11',
    appointmentDate: '2026-05-28',
    closedDate: null,
    outcome: 'Pending',
    coordinatorName: 'Sarah Johnson',
    notes: 'A1C 6.2% — pre-diabetic. Postpartum context. 47 miles to Prairie Health Services.',
    daysOpen: 5,
  },
  {
    id: 'ref-002',
    patientName: 'Maria Redhawk',
    patientId: 'patient-maria',
    referralDate: '2026-04-18',
    specialty: 'Behavioral Health',
    urgency: 'Routine',
    status: 'Assigned',
    assignedProvider: 'Dr. Sarah Nakamura — Cedar Valley Behavioral Health',
    providerId: 'prov-012',
    providerTier: 'Preferred',
    icdCode: 'F53.0',
    icdDescription: 'Postpartum depression (Edinburgh PND 427d)',
    submissionChannel: 'Direct Message',
    submittedDate: '2026-04-19',
    appointmentDate: '2026-05-05',
    closedDate: null,
    outcome: 'Pending',
    coordinatorName: 'Sarah Johnson',
    notes: 'Edinburgh PND screening overdue 427 days. Postpartum support group referral.',
    daysOpen: 7,
  },
  {
    id: 'ref-003',
    patientName: 'Margaret Okonkwo',
    patientId: 'patient-001',
    referralDate: '2026-04-12',
    specialty: 'Nephrology',
    urgency: 'STAT',
    status: 'Awaiting EMR',
    assignedProvider: 'Dr. Priya Venkataraman — Cedar Valley Nephrology',
    providerId: 'prov-004',
    providerTier: 'Preferred',
    icdCode: 'N18.4',
    icdDescription: 'Chronic kidney disease, stage 4',
    submissionChannel: null,
    submittedDate: null,
    appointmentDate: null,
    closedDate: null,
    outcome: 'Pending',
    coordinatorName: 'Sarah Johnson',
    notes: 'Urgent — GFR declining rapidly. 89 miles to Cedar Valley Critical Access Hospital.',
    daysOpen: 3,
  },
  {
    id: 'ref-004',
    patientName: 'Bernard Thibodeau',
    patientId: 'patient-004',
    referralDate: '2026-04-05',
    specialty: 'Cardiology',
    urgency: 'Routine',
    status: 'Completed',
    assignedProvider: 'Dr. Amara Osei — Summit Regional Cardiology',
    providerId: 'prov-001',
    providerTier: 'Preferred',
    icdCode: 'I10',
    icdDescription: 'Essential hypertension',
    submissionChannel: 'Epic Direct',
    submittedDate: '2026-04-06',
    appointmentDate: '2026-04-13',
    closedDate: '2026-04-13',
    outcome: 'Seen',
    coordinatorName: 'Sarah Johnson',
    notes: 'Follow-up in 3 months. 112 miles to Summit Regional — Rapid City.',
    daysOpen: 8,
  },
  {
    id: 'ref-005',
    patientName: 'Constance Abara',
    patientId: 'patient-005',
    referralDate: '2026-04-11',
    specialty: 'Endocrinology',
    urgency: 'Routine',
    status: 'Pending',
    assignedProvider: null,
    providerId: null,
    providerTier: null,
    icdCode: 'E11.9',
    icdDescription: 'Type 2 diabetes mellitus',
    submissionChannel: null,
    submittedDate: null,
    appointmentDate: null,
    closedDate: null,
    outcome: null,
    coordinatorName: 'Sarah Johnson',
    notes: 'A1c > 10, needs specialist review. 78 miles to Gregory County.',
    daysOpen: 4,
  },
  {
    id: 'ref-006',
    patientName: 'Walter Przybylski',
    patientId: 'patient-006',
    referralDate: '2026-04-09',
    specialty: 'Gastroenterology',
    urgency: 'Routine',
    status: 'Assigned',
    assignedProvider: 'Dr. Thomas Kaczmarek — Riverside Medical Associates',
    providerId: 'prov-007',
    providerTier: 'In-Network',
    icdCode: 'K57.30',
    icdDescription: 'Diverticulosis of large intestine',
    submissionChannel: 'Phone',
    submittedDate: '2026-04-10',
    appointmentDate: '2026-04-25',
    closedDate: null,
    outcome: 'Pending',
    coordinatorName: 'Sarah Johnson',
    notes: 'Colonoscopy prep instructions sent.',
    daysOpen: 6,
  },
  {
    id: 'ref-007',
    patientName: 'Maria Redhawk',
    patientId: 'patient-maria',
    referralDate: '2026-04-01',
    specialty: 'Family Medicine',
    urgency: 'Routine',
    status: 'Completed',
    assignedProvider: 'Dr. Carlos Mendez-Ruiz — Prairie Health Services',
    providerId: 'prov-009',
    providerTier: 'Preferred',
    icdCode: 'Z39.1',
    icdDescription: 'Care for lactating mother',
    submissionChannel: 'Epic Direct',
    submittedDate: '2026-04-02',
    appointmentDate: '2026-04-08',
    closedDate: '2026-04-08',
    outcome: 'Seen',
    coordinatorName: 'Sarah Johnson',
    notes: 'Postpartum follow-up. 12 miles from Martin SD.',
    daysOpen: 7,
  },
  {
    id: 'ref-008',
    patientName: 'Sylvia Montecinos',
    patientId: 'patient-011',
    referralDate: '2026-04-13',
    specialty: 'Cardiology',
    urgency: 'STAT',
    status: 'In Progress',
    assignedProvider: 'Dr. Amara Osei — Summit Regional Cardiology',
    providerId: 'prov-001',
    providerTier: 'Preferred',
    icdCode: 'I48.0',
    icdDescription: 'Paroxysmal atrial fibrillation',
    submissionChannel: 'Epic Direct',
    submittedDate: '2026-04-13',
    appointmentDate: '2026-04-15',
    closedDate: null,
    outcome: 'Pending',
    coordinatorName: 'Sarah Johnson',
    notes: 'Holter monitor ordered. 147 miles to Summit Regional — Rapid City.',
    daysOpen: 2,
  },
  {
    id: 'ref-009',
    patientName: 'Kwame Asantewaa',
    patientId: 'patient-012',
    referralDate: '2026-04-07',
    specialty: 'Orthopedics',
    urgency: 'Routine',
    status: 'Completed',
    assignedProvider: 'Dr. Jerome Blackwood — Southridge Specialist Network',
    providerId: 'prov-005',
    providerTier: 'In-Network',
    icdCode: 'M17.11',
    icdDescription: 'Primary osteoarthritis, right knee',
    submissionChannel: 'Fax',
    submittedDate: '2026-04-08',
    appointmentDate: '2026-04-14',
    closedDate: '2026-04-14',
    outcome: 'Seen',
    coordinatorName: 'Sarah Johnson',
    notes: 'X-ray reviewed, PT referral added. 112 miles to Hot Springs SD.',
    daysOpen: 7,
  },
  {
    id: 'ref-010',
    patientName: 'Rosa Evangelista',
    patientId: 'patient-003',
    referralDate: '2026-04-03',
    specialty: 'Endocrinology',
    urgency: 'Urgent',
    status: 'Completed',
    assignedProvider: 'Dr. Nkechi Eze-Williams — Badlands PCP',
    providerId: 'prov-008',
    providerTier: 'Preferred',
    icdCode: 'E10.65',
    icdDescription: 'Type 1 diabetes with hyperglycemia',
    submissionChannel: 'Phone',
    submittedDate: '2026-04-04',
    appointmentDate: '2026-04-10',
    closedDate: '2026-04-10',
    outcome: 'Seen',
    coordinatorName: 'Sarah Johnson',
    notes: 'Tribal Health Program Administration. 38 miles from Pine Ridge.',
    daysOpen: 7,
  },
  {
    id: 'ref-011',
    patientName: 'Bernard Thibodeau',
    patientId: 'patient-004',
    referralDate: '2026-04-14',
    specialty: 'Geriatrics',
    urgency: 'Routine',
    status: 'Pending',
    assignedProvider: null,
    providerId: null,
    providerTier: null,
    icdCode: 'Z87.39',
    icdDescription: 'Personal history of other musculoskeletal disorders',
    submissionChannel: null,
    submittedDate: null,
    appointmentDate: null,
    closedDate: null,
    outcome: null,
    coordinatorName: 'Sarah Johnson',
    notes: 'Comprehensive geriatric assessment needed.',
    daysOpen: 1,
  },
  {
    id: 'ref-012',
    patientName: 'Delroy Hutchinson',
    patientId: 'patient-002',
    referralDate: '2026-03-28',
    specialty: 'Cardiology',
    urgency: 'Urgent',
    status: 'Completed',
    assignedProvider: 'Dr. Amara Osei — Summit Regional Cardiology',
    providerId: 'prov-001',
    providerTier: 'Preferred',
    icdCode: 'I25.10',
    icdDescription: 'Atherosclerotic heart disease',
    submissionChannel: 'Epic Direct',
    submittedDate: '2026-03-29',
    appointmentDate: '2026-04-04',
    closedDate: '2026-04-04',
    outcome: 'Seen',
    coordinatorName: 'Sarah Johnson',
    notes: 'Stress test ordered. 147 miles to Summit Regional — Rapid City.',
    daysOpen: 7,
  },
];
