/**
 * BFF Route — POST /api/mtm/detected-issues
 *
 * Receives: { findings: MtmFinding[], context: DetectedIssueContext }
 * Returns:  { savedIds: string[] }
 *
 * Writes each MtmFinding as a FHIR R4 DetectedIssue to the store
 * (in-memory mock or HAPI FHIR, via getFhirClient()).
 *
 * This is called AFTER the physician has acknowledged all findings and the
 * MedicationRequest has been saved — so newMedicationRequestId is available.
 *
 * Da Vinci MTM pattern: DetectedIssue carries the finding artifact; downstream
 * Task/CarePlan/CommunicationRequest are generated by the care-management workflow.
 *
 * INVARIANT: No PHI stored by this route. Server-side only.
 */
import { NextRequest, NextResponse } from 'next/server';
import { getFhirClient } from '@/lib/services/fhirClient';
import { buildDetectedIssues } from '@/lib/agents/mtm/fhirDetectedIssue';
import type { MtmFinding } from '@/lib/agents/mtm/types';
import type { DetectedIssueContext } from '@/lib/agents/mtm/fhirDetectedIssue';

export async function POST(req: NextRequest): Promise<NextResponse> {
  let findings: MtmFinding[];
  let context: DetectedIssueContext;

  try {
    const body = (await req.json()) as { findings?: unknown; context?: unknown };
    if (
      !Array.isArray(body.findings) ||
      typeof body.context !== 'object' ||
      body.context === null
    ) {
      return NextResponse.json({ error: 'findings[] and context{} are required' }, { status: 400 });
    }
    findings = body.findings as MtmFinding[];
    context = body.context as DetectedIssueContext;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  if (findings.length === 0) {
    return NextResponse.json({ savedIds: [] });
  }

  try {
    const resources = buildDetectedIssues(findings, context);
    const client = getFhirClient();

    const savedIds: string[] = [];
    for (const resource of resources) {
      // cast through unknown — FhirDetectedIssue is a narrower type than the generic Record
      const created = await client.create<{ id?: string }>(
        resource as unknown as Record<string, unknown>
      );
      if (created.id) savedIds.push(created.id);
    }

    return NextResponse.json({ savedIds });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: message, savedIds: [] }, { status: 502 });
  }
}
