/**
 * The runtime CRD is wired to the policy engine: coverageRuleForCode reads engine-published rules,
 * not the seed. Proves the authoring→publication→runtime loop drives the live screen's data.
 */
import { describe, it, expect } from 'vitest';
import {
  engineCoverageRuleForCode,
  engineStore,
  engineDtrMatchForCode,
} from '@/lib/pa/policyEngineBridge';
import { coverageRuleForCode } from '@/lib/pa/publishedCoverage';
import { runtimeCrd } from '@/lib/policy/encode';

describe('CRD reads engine-published coverage rules', () => {
  it('a demo code resolves to an engine-published rule (verbatim criteria, doc-needed, Dx)', () => {
    const rule = engineCoverageRuleForCode('72148');
    expect(rule).toBeDefined();
    expect(rule?.priorAuthRequired).toBe(true);
    expect(rule?.criteriaNames).toContain('Neurological deficit / red-flag findings');
    expect((rule?.docNeeded ?? []).length).toBeGreaterThan(0);
    expect(rule?.primaryDx?.code).toBe('M54.16');
    // the questionnaire canonical is generated by the engine, not a hand-written seed slug
    expect(rule?.questionnaireCanonical).toContain('urn:rhtp:dtr/Questionnaire/');
  });

  it('coverageRuleForCode serves the engine rule for a published code', () => {
    const viaSeamRule = coverageRuleForCode('27447');
    const viaEngine = engineCoverageRuleForCode('27447');
    expect(viaEngine).toBeDefined();
    expect(viaSeamRule.questionnaireCanonical).toBe(viaEngine?.questionnaireCanonical);
    expect(viaSeamRule.clinicalGuideline).toBe('Musculoskeletal Surgery v2025-04');
  });

  it('an unpublished code is not served by the engine (falls back, fail-honest PA-required)', () => {
    expect(engineCoverageRuleForCode('00000')).toBeUndefined();
    const fallback = coverageRuleForCode('00000');
    expect(fallback.priorAuthRequired).toBe(true); // never silently waved through
  });

  it('DTR match is projected from the engine Questionnaire (real criteria, not a mock)', () => {
    const dtr = engineDtrMatchForCode('72148');
    expect(dtr).not.toBeNull();
    expect(dtr?.cptCode).toBe('72148');
    expect(dtr?.policyTitle).toContain('CPT 72148');
    // the authored criteria appear as requirement groups
    const titles = (dtr?.groups ?? []).map((g) => g.title);
    expect(titles).toContain('Neurological deficit / red-flag findings');
    // documentation-needed items are present as groups too
    expect(titles).toContain('Physical therapy notes');
    // nothing is pre-satisfied (no fabricated evidence); groups start un-met
    expect((dtr?.groups ?? []).every((g) => g.status !== 'met')).toBe(true);
    expect(dtr?.allMet).toBe(false);
  });

  it('an unpublished code yields no engine DTR (caller falls back)', () => {
    expect(engineDtrMatchForCode('00000')).toBeNull();
  });

  it('the engine store actually evaluates a patient for a published code', () => {
    const store = engineStore();
    // BMI/eligibility facts are attestation-based for these imaging/surgery demos; a request with
    // the published code resolves to a real coverage-information payload, not a stub.
    const res = runtimeCrd(store, '95810', { measures: {} });
    expect(res.published).toBe(true);
    expect(res.coverage.questionnaireCanonical).toContain('urn:rhtp:dtr/Questionnaire/');
    expect(res.coverage.criteriaNames.length).toBeGreaterThan(0);
  });
});
